import type { ChecklistGroup, ChecklistStep, NicNacAnswer, Resource } from './types';

export const groups: ChecklistGroup[] = [
  'Get Connected',
  'Start BPU',
  'Pay And Payouts',
  'Build Your Setup',
  'Shipping And Orders',
  'Loyalty And Follow-Up',
  'Questions for Brittany',
];

export const resources: Resource[] = [
  {
    id: 'team-facebook-intro',
    title: 'Team Intro Checklist',
    description: 'Brittany team guidance: send a Facebook friend request and a picture for the team announcement.',
    url: '',
    sourceType: 'team',
    category: 'Start Here',
  },
  {
    id: 'team-social-growth',
    title: 'Follower And Linktree Goal',
    description: 'Team guidance: work toward 1,000 followers so a Linktree can be created when the account is ready.',
    url: '',
    sourceType: 'team',
    category: 'Start Here',
  },
  {
    id: 'bp-enrollment-guide',
    title: 'Bomb Party New Rep Enrollment Guide',
    description: 'Official guide for enrolling as a Party Rep.',
    url: 'https://bombpartyassets.blob.core.windows.net/exigoresourcelibraryassets/Enrolling%20as%20a%20Party%20Rep-2024.pdf',
    sourceType: 'official',
    category: 'Start Here',
  },
  {
    id: 'bpu-enrollment-guide',
    title: 'Bomb Party University Access Guide',
    description: 'Use BPU as the official training source. This site only helps you get logged in, know what to start, and capture questions for Brittany.',
    details: [
      'Look for the email titled "Confirm Your Email Account for Bomb Party University."',
      'Click the login button from that email and use the same email address you used when enrolling as a rep.',
      'Watch for the 6-digit login code email, then enter the code in BPU.',
      'Accept the BPU and Teachable terms when prompted.',
      'Start the first new-rep course, "Start Strong and Get Fizzing!"',
      'If BPU shows a completion screen or certificate, save a screenshot for Brittany. Do not assume one will appear.',
      'If the login email, code, or course access does not work, ask Brittany instead of guessing.',
    ],
    url: 'https://bombpartyassets.blob.core.windows.net/exigoresourcelibraryassets/How%20to%20Guide%20Your%20Downline%20Through%20the%20BPU%20Enrollment%20Process%2011.1.24.pdf',
    sourceType: 'official',
    category: 'BPU',
  },
  {
    id: 'payquicker-setup',
    title: 'PayQuicker Setup Reminder',
    description: 'Team guidance: watch for the PayQuicker email, complete setup, and wait for the pay card to be mailed.',
    url: '',
    sourceType: 'team',
    category: 'Money',
  },
  {
    id: 'team-payout-notes',
    title: 'Team Payout Notes',
    description: 'Brittany notes about weekly sales payouts and monthly bonus timing. Needs official wording before final publishing.',
    url: '',
    sourceType: 'team',
    category: 'Money',
  },
  {
    id: 'bp-income-disclosure',
    title: 'Bomb Party Income Disclosure Statement',
    description: 'Official income disclosure for compliance-aware business basics.',
    url: 'https://bombpartyassets.blob.core.windows.net/exigoresourcelibraryassets/Rep%20Use%20Documents/Bomb%20Party_Income%20Disclosure%20Statement_2025%20%281%29.pdf',
    sourceType: 'official',
    category: 'Money',
  },
  {
    id: 'ftc-mlm-guidance',
    title: 'FTC MLM Guidance',
    description: 'Plain compliance backstop for avoiding income and lifestyle claims.',
    url: 'https://www.ftc.gov/business-guidance/resources/business-guidance-concerning-multi-level-marketing',
    sourceType: 'official',
    category: 'Money',
  },
  {
    id: 'amazon-supply-list',
    title: 'Amazon Supply List',
    description: 'Brittany starter supply examples from the Amazon list. Open each item in Amazon when you are ready to compare or buy.',
    details: [
      {
        label: 'BOPART small mesh zipper pouch bags, 24 pack',
        url: 'https://www.amazon.com/dp/B0CKQN1JPW',
        note: 'Organization',
      },
      {
        label: 'iMBAPrice #0 hot pink poly bubble mailers, 250 pack',
        url: 'https://www.amazon.com/dp/B074GJ3VHH',
        note: 'Shipping',
      },
      {
        label: 'iMBAPrice 8.5 x 12 hot pink poly bubble mailers, 100 pack',
        url: 'https://www.amazon.com/dp/B074GFFKSC',
        note: 'Shipping',
      },
      {
        label: 'Sasylvia jewelry ring gift boxes with foam insert, 200 pack',
        url: 'https://www.amazon.com/dp/B0DQL359SK',
        note: 'Packaging',
      },
      {
        label: 'SATINIOR clear small plastic containers with hinged lid, 48 pack',
        url: 'https://www.amazon.com/dp/B09CKW25VF',
        note: 'Organization',
      },
      {
        label: 'L Liked numbered raffle tickets roll',
        url: 'https://www.amazon.com/dp/B0BB6Y6QV1',
        note: 'Customer fun',
      },
      {
        label: 'Elite Gourmet countertop electric burner',
        url: 'https://www.amazon.com/dp/B09G99VMB7',
        note: 'Live setup',
      },
      {
        label: 'Phomemo Bluetooth 4 x 6 thermal shipping label printer',
        url: 'https://www.amazon.com/dp/B0BTYD7H28',
        note: 'Shipping',
      },
      {
        label: 'WORKPRO retractable utility knife and blades',
        url: 'https://www.amazon.com/dp/B0C6KQ9HRZ',
        note: 'Shipping',
      },
      {
        label: 'XJLVSV clear glass saucepan with lid',
        url: 'https://www.amazon.com/dp/B0B693MY6V',
        note: 'Live setup',
      },
      {
        label: 'NEEWER 18 inch ring light kit with stand and phone holder',
        url: 'https://www.amazon.com/dp/B01LXDNNBW',
        note: 'Live setup',
      },
      {
        label: 'UMETDO mesh zipper pouch bags, 24 pack assorted sizes',
        url: 'https://www.amazon.com/dp/B0CC67GJSK',
        note: 'Organization',
      },
    ],
    url: '',
    sourceType: 'team',
    category: 'Supplies',
  },
  {
    id: 'setup-lighting-note',
    title: 'Setup And Lighting Note',
    description: 'Team guidance: make sure the first-live setup is ready and the lighting looks good.',
    url: '',
    sourceType: 'team',
    category: 'Supplies',
  },
  {
    id: 'shipcom-setup-note',
    title: 'Ship.com Setup Note',
    description: 'Brittany team guidance: sign up through the back office and use the required $19 package.',
    url: '',
    sourceType: 'team',
    category: 'Shipping',
  },
  {
    id: 'shipping-video-placeholder',
    title: 'Shipping And Label Videos',
    description: 'Brittany walkthrough videos for shipping, labels, and the first shipping-day flow.',
    details: [
      {
        label: 'Shipping walkthrough from Brittany',
        url: '/videos/brittany-shipping-walkthrough.mp4',
        note: 'Video, about 1 minute 43 seconds',
        kind: 'video',
      },
      {
        label: 'Labels walkthrough from Brittany',
        url: '/videos/brittany-labels-walkthrough.mp4',
        note: 'Video, about 33 seconds',
        kind: 'video',
      },
    ],
    url: '',
    sourceType: 'team',
    category: 'Shipping',
  },
  {
    id: 'bp-shipping-policy',
    title: 'Bomb Party Shipping Policy',
    description: 'Official shipping policy resource.',
    url: 'https://bombpartysupport.zendesk.com/hc/en-us/articles/33220290467732-Shipping-Policy',
    sourceType: 'official',
    category: 'Shipping',
  },
  {
    id: 'bp-return-policy',
    title: 'Bomb Party Return Policy',
    description: 'Official return and reveal issue policy resource.',
    url: 'https://help.bombparty.com/hc/en-us/articles/33194356359444-Return-Policy',
    sourceType: 'official',
    category: 'Shipping',
  },
  {
    id: 'loyalty-program-example',
    title: '15 Fizz Points Loyalty Example',
    description: 'Team guidance: one example loyalty setup is 15 points, one point per item, then a free OG item. Needs Brittany approval before final publishing.',
    url: '',
    sourceType: 'team',
    category: 'Loyalty',
  },
  {
    id: 'sparkle-suite-preview',
    title: 'Sparkle Suite Next Step',
    description: 'Soft handoff for reps who are ready for a public site, customer resources, live queue, and dance floor tools.',
    url: '',
    sourceType: 'sparkle-suite',
    category: 'Sparkle Suite',
  },
];

export const steps: ChecklistStep[] = [
  {
    id: 'facebook-team-intro',
    group: 'Get Connected',
    title: 'Connect with Brittany and send your team picture',
    shortTitle: 'Team intro',
    dayWindow: 'Day 1',
    whatToDo: 'Send Brittany a Facebook friend request. Then send the picture she should use to announce you to the team.',
    whyItMatters: 'This gets you connected to the team and gives your leader what she needs to introduce you.',
    resourceIds: ['team-facebook-intro'],
    brittanyNote: 'Brittany source note: "Send me a friend request on Facebook. Send me a picture to announce to the team."',
    nicNacHint: 'Ask me what to send Brittany first.',
  },
  {
    id: 'followers-linktree',
    group: 'Get Connected',
    title: 'Start working toward 1,000 followers',
    shortTitle: 'Follower goal',
    dayWindow: 'Early goal',
    whatToDo: 'Start building toward 1,000 followers. When you are ready, Brittany can help you create a Linktree or simple link hub.',
    whyItMatters: 'A link hub makes it easier for customers to find your important links once your social account is ready for it.',
    resourceIds: ['team-social-growth'],
    brittanyNote: 'Brittany source note: "Work on gaining a 1000 followers so we can create a link tree." Confirm whether this is needed before the first live or just an early goal.',
    nicNacHint: 'Ask me why the 1,000 follower goal matters.',
  },
  {
    id: 'bpu-login',
    group: 'Start BPU',
    title: 'Get into Bomb Party University',
    shortTitle: 'BPU access',
    dayWindow: 'Day 1',
    whatToDo: 'Find the email titled "Confirm Your Email Account for Bomb Party University." Log in with the email you used to enroll, enter the 6-digit code, accept the BPU/Teachable terms, and start "Start Strong and Get Fizzing!"',
    whyItMatters: 'BPU is the official training source. Britt\'s site helps you get there, stay organized, and save questions, but it does not replace BPU.',
    resourceIds: ['bpu-enrollment-guide'],
    brittanyNote: 'Brittany source note: "BPU will teach you everything you need to know on how to get started."',
    nicNacHint: 'Ask me how to get into BPU or what to do after logging in.',
  },
  {
    id: 'payquicker-setup',
    group: 'Pay And Payouts',
    title: 'Complete your PayQuicker setup',
    shortTitle: 'PayQuicker',
    dayWindow: 'When email arrives',
    whatToDo: 'Watch for the PayQuicker email. Complete the setup so your card can be mailed to you.',
    whyItMatters: 'Brittany says PayQuicker is how reps get paid, and the card acts like a debit card.',
    resourceIds: ['payquicker-setup'],
    brittanyNote: 'Brittany source note: PayQuicker will send an email that needs to be completed to get your card mailed. Confirm exact PayQuicker steps before final publishing.',
    nicNacHint: 'Ask me what PayQuicker is.',
  },
  {
    id: 'payout-basics',
    group: 'Pay And Payouts',
    title: 'Understand the basic payout rhythm',
    shortTitle: 'Payout basics',
    dayWindow: 'Week 1',
    whatToDo: 'Know the rough rhythm: sales payouts are described by Brittany as weekly on Thursdays, and monthly bonus payouts are described as around the 15th. Always confirm details in official Bomb Party and PayQuicker sources.',
    whyItMatters: 'Money questions can get confusing fast. Keep expectations clear and ask before making decisions based on payout timing.',
    resourceIds: ['team-payout-notes', 'bp-income-disclosure', 'ftc-mlm-guidance'],
    brittanyNote: 'Team guidance only: weekends, holidays, account status, qualifying activity, and official Bomb Party rules may affect timing or eligibility.',
    nicNacHint: 'Ask me when payouts usually happen.',
  },
  {
    id: 'supplies-ready',
    group: 'Build Your Setup',
    title: 'Gather your first-live supplies',
    shortTitle: 'Supplies',
    dayWindow: 'Before first live',
    whatToDo: 'Open Brittany\'s Amazon supply list below and review the starter items for your first shows and first shipping day.',
    whyItMatters: 'Having supplies ready before orders come in keeps the first live and first shipping day calmer.',
    resourceIds: ['amazon-supply-list'],
    brittanyNote: 'Brittany source note: she sent an Amazon supply list with examples for getting set up. Treat these as Brittany\'s starter examples, then confirm any must-have versus nice-to-have items before buying everything.',
    nicNacHint: 'Ask me what supplies Brittany recommends.',
  },
  {
    id: 'setup-lighting',
    group: 'Build Your Setup',
    title: 'Check your setup and lighting',
    shortTitle: 'Lighting',
    dayWindow: 'Before first live',
    whatToDo: 'Set up your live area before you go live. Check your camera angle, work surface, and lighting.',
    whyItMatters: 'Good lighting and a ready setup make it easier for customers to see the reveals and easier for you to stay calm.',
    resourceIds: ['setup-lighting-note'],
    brittanyNote: 'Brittany source note: "Make sure your setup is ready to go, lighting is great."',
    nicNacHint: 'Ask me how to check my setup before going live.',
  },
  {
    id: 'shipcom-setup',
    group: 'Shipping And Orders',
    title: 'Set up Ship.com from your back office',
    shortTitle: 'Ship.com setup',
    dayWindow: 'Before first orders',
    whatToDo: 'Sign up with Ship.com through your back office and choose the $19 membership package.',
    whyItMatters: 'Shipping setup needs to be ready before you have customer orders waiting on labels.',
    resourceIds: ['shipcom-setup-note'],
    brittanyNote: 'Brittany team guidance: Ship.com and the $19 package are required setup tools for this team.',
    nicNacHint: 'Ask me what Ship.com is for.',
  },
  {
    id: 'shipping-orders',
    group: 'Shipping And Orders',
    title: 'Merge orders before buying labels',
    shortTitle: 'Merge orders',
    dayWindow: 'First shipping day',
    whatToDo: 'Watch Brittany\'s shipping videos. When it is time to ship, first merge orders for customers who ordered more than one time. Then purchase labels.',
    whyItMatters: 'Merging repeat customer orders before buying labels can prevent extra labels and keep shipping cleaner. The videos give reps something visual to follow instead of guessing.',
    resourceIds: ['shipping-video-placeholder', 'bp-shipping-policy', 'bp-return-policy'],
    brittanyNote: 'Brittany source note: she sent two videos for shipping and labels. Confirm final titles if she wants these labeled more specifically.',
    nicNacHint: 'Ask me what to do before buying shipping labels.',
  },
  {
    id: 'loyalty-points',
    group: 'Loyalty And Follow-Up',
    title: 'Review the optional 15 fizz points example',
    shortTitle: 'Loyalty points',
    dayWindow: 'After basics',
    whatToDo: 'If you want to use a loyalty program, review Brittany\'s example: 15 fizz points, one point per item, then a free OG earring, necklace, or ring. After redemption, the points start over.',
    whyItMatters: 'A simple loyalty program can help customers understand how rewards work, but it needs to be tracked carefully.',
    resourceIds: ['loyalty-program-example'],
    brittanyNote: 'Team guidance only: Brittany says the free OG item is taken out as personal use. Confirm final wording before publishing because this touches inventory/accounting handling.',
    nicNacHint: 'Ask me how the 15 fizz points example works.',
  },
  {
    id: 'questions-for-brittany',
    group: 'Questions for Brittany',
    title: 'Save anything that needs a team-lead answer',
    shortTitle: 'Ask Brittany',
    dayWindow: 'Any time',
    whatToDo: 'If the answer affects your account, money, inventory, policy, taxes, or a customer situation, save it here for Brittany instead of guessing.',
    whyItMatters: 'Some answers should come from Brittany, Bomb Party support, or official resources. It is better to ask than to build a habit around a guess.',
    resourceIds: ['sparkle-suite-preview'],
    brittanyNote: 'Use this area to capture questions that Nic-Nac should not answer from onboarding content alone.',
    nicNacHint: 'Ask me what should be escalated to Brittany.',
  },
];

export const nicNacAnswers: NicNacAnswer[] = [
  {
    id: 'pay-sensitive',
    triggers: ['tax', 'taxes', 'accounting', 'personal use', 'write off', 'write-off', 'guarantee', 'guaranteed', 'income claim', 'exact payout', 'missing payout'],
    response: 'That needs a careful answer. I saved it for Brittany because taxes, accounting, exact payouts, and account-specific money issues should not be answered from onboarding content alone.',
    resourceIds: ['bp-income-disclosure', 'ftc-mlm-guidance'],
    shouldEscalate: true,
  },
  {
    id: 'inventory-sensitive',
    triggers: ['buy more inventory', 'more inventory', 'should i buy', 'how much inventory', 'big spend', 'spend money'],
    response: 'Do not make a big inventory spend from excitement alone. Review the official income disclosure and ask Brittany before making a large purchase. I saved this question for her.',
    resourceIds: ['bp-income-disclosure', 'ftc-mlm-guidance'],
    shouldEscalate: true,
  },
  {
    id: 'first-steps',
    triggers: ['what do i do first', 'first step', 'where do i start', 'start first'],
    response: 'Start simple: connect with Brittany on Facebook, send your team announcement picture, then get into BPU. After that, watch for PayQuicker and begin gathering supplies.',
    resourceIds: ['team-facebook-intro', 'bpu-enrollment-guide', 'payquicker-setup'],
    shouldEscalate: false,
  },
  {
    id: 'facebook-intro',
    triggers: ['facebook', 'friend request', 'picture', 'photo', 'announce', 'announcement'],
    response: 'Send Brittany a Facebook friend request, then send the picture she should use to announce you to the team.',
    resourceIds: ['team-facebook-intro'],
    shouldEscalate: false,
  },
  {
    id: 'followers-linktree',
    triggers: ['1000', '1,000', 'followers', 'linktree', 'link tree', 'link hub'],
    response: 'Brittany wants new reps working toward 1,000 followers so a Linktree or simple link hub can be created when the account is ready.',
    resourceIds: ['team-social-growth'],
    shouldEscalate: false,
  },
  {
    id: 'bpu-first',
    triggers: ['first in bpu', 'start in bpu', 'do first', 'first lesson', 'after i login', 'after login', 'start strong and get fizzing', 'get fizzing'],
    response: 'After you get into BPU, start the first new-rep course, "Start Strong and Get Fizzing!" Complete what BPU asks you to complete, and write down anything confusing for Brittany. The goal is to use BPU as the official training source.',
    resourceIds: ['bpu-enrollment-guide'],
    shouldEscalate: false,
  },
  {
    id: 'bpu',
    triggers: ['bpu', 'university', 'teachable', 'login', 'training', 'password', 'email', '6 digit', 'six digit', 'code'],
    response: 'BPU is Bomb Party University, the official place to learn how to get started. Look for the "Confirm Your Email Account for Bomb Party University" email, log in with your enrollment email, enter the 6-digit code, accept the terms, and start the first course. Ask Brittany if the email, code, or access does not work.',
    resourceIds: ['bpu-enrollment-guide'],
    shouldEscalate: false,
  },
  {
    id: 'bpu-completion',
    triggers: ['certificate', 'completion', 'completed bpu', 'finish bpu', 'finished bpu', 'prove i finished', 'screenshot'],
    response: 'We do not have confirmation that BPU always gives a certificate. Complete the BPU course work it gives you. If BPU shows a completion screen or certificate, save a screenshot for Brittany. If nothing appears, just note that you completed the course and ask Brittany if she wants anything else.',
    resourceIds: ['bpu-enrollment-guide'],
    shouldEscalate: false,
  },
  {
    id: 'payquicker',
    triggers: ['payquicker', 'pay quicker', 'card', 'debit card', 'get paid', 'paid'],
    response: 'Watch for the PayQuicker email and complete the setup. Brittany says the card acts like a debit card and is how reps get paid.',
    resourceIds: ['payquicker-setup'],
    shouldEscalate: false,
  },
  {
    id: 'payouts',
    triggers: ['payout', 'payouts', 'bp wallet', 'bonus', '15th', 'thursday', 'weekly', 'monthly'],
    response: 'Team guidance says sales payouts are usually weekly on Thursdays from the BP wallet to PayQuicker, and monthly bonus payouts are around the 15th. Weekend, holiday, account, and official rule details can change timing, so confirm anything important.',
    resourceIds: ['team-payout-notes', 'bp-income-disclosure'],
    shouldEscalate: false,
  },
  {
    id: 'hard-truths',
    triggers: ['hard truth', 'hard truths', 'real talk', 'truths', 'what should i know', 'what do new reps need to know', 'honest'],
    response: 'Hard-but-helpful truths: this is a real small business, not guaranteed income. Quiet rooms happen. Buying more inventory does not automatically create customers. Official policy beats memory. Learn the system, stay consistent, and ask Brittany before big money or inventory decisions.',
    resourceIds: ['bp-income-disclosure', 'ftc-mlm-guidance'],
    shouldEscalate: false,
  },
  {
    id: 'supplies',
    triggers: ['supplies', 'amazon', 'equipment', 'labels', 'packaging', 'fizz setup'],
    response: 'Brittany\'s starter examples are linked in the Amazon Supply List resource. It includes organization pouches and containers, mailers, a label printer, a utility knife, a burner, a glass saucepan, a ring light, jewelry boxes, and raffle tickets. Confirm what is must-have before buying everything.',
    resourceIds: ['amazon-supply-list'],
    shouldEscalate: false,
  },
  {
    id: 'lighting',
    triggers: ['lighting', 'lightening', 'setup', 'camera', 'phone', 'ready to go'],
    response: 'Before your first live, check your setup, camera angle, work surface, and lighting. Good lighting helps customers see the reveal and helps you feel more prepared.',
    resourceIds: ['setup-lighting-note'],
    shouldEscalate: false,
  },
  {
    id: 'shipcom',
    triggers: ['ship.com', 'ship com', 'shipping account', '19', '$19', 'membership package'],
    response: 'Brittany says to sign up with Ship.com through the back office and use the $19 membership package. Treat this as required team setup.',
    resourceIds: ['shipcom-setup-note'],
    shouldEscalate: false,
  },
  {
    id: 'merge-labels',
    triggers: ['merge', 'merge orders', 'labels', 'purchase labels', 'shipping labels'],
    response: 'When it is time to ship, team guidance says to merge orders first for customers who ordered more than once, then purchase labels. Watch Brittany\'s shipping and labels videos in this step before your first shipping day.',
    resourceIds: ['shipping-video-placeholder', 'bp-shipping-policy'],
    shouldEscalate: false,
  },
  {
    id: 'shipping',
    triggers: ['shipping', 'ship', 'tracking', 'return', 'damaged', 'defective', 'replacement'],
    response: 'For shipping and return policy details, use the official Bomb Party resources. For a specific customer situation, ask Brittany or Bomb Party support.',
    resourceIds: ['bp-shipping-policy', 'bp-return-policy'],
    shouldEscalate: false,
  },
  {
    id: 'loyalty',
    triggers: ['loyalty', 'fizz points', 'points', '15 points', 'free og', 'free ring', 'free earring', 'free necklace', 'redeem'],
    response: 'Brittany gave an example loyalty setup: 15 fizz points, one point per item, then a free OG earring, necklace, or ring. Once redeemed, points start over. Ask Brittany before finalizing how to track or record free items.',
    resourceIds: ['loyalty-program-example'],
    shouldEscalate: false,
  },
  {
    id: 'sparkle-suite',
    triggers: ['website', 'live queue', 'customers', 'dance floor', 'sparkle suite', 'rep tools'],
    response: 'Sparkle Suite can help reps with a public site, customer resources, live queue support, and future tools once the basics are in place. For now, finish your onboarding steps first.',
    resourceIds: ['sparkle-suite-preview'],
    shouldEscalate: false,
  },
];
