'use client'
import { ChevronDown } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { OperatorOnboardingChecklistItem } from '@/lib/control-center/operator-onboarding-checklist'

export function OperatorOnboardingChecklist({ clientName, initialItems, repId }: { clientName: string; initialItems: OperatorOnboardingChecklistItem[]; repId: string }) {
  const [items, setItems] = useState(initialItems); const [savingKey, setSavingKey] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null)
  const completeCount = useMemo(() => items.filter((item) => item.entry.isCompleted).length, [items])
  async function toggle(item: OperatorOnboardingChecklistItem) { const isCompleted = !item.entry.isCompleted; setSavingKey(item.key); setMessage(null); try { const response = await fetch('/api/control-center/onboarding-checklist', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ repId, itemKey: item.key, isCompleted }) }); const body = (await response.json()) as { error?: string; item?: OperatorOnboardingChecklistItem['entry'] }; if (!response.ok || !body.item) throw new Error(body.error ?? 'Unable to update this item.'); setItems((current) => current.map((candidate) => candidate.key === item.key ? { ...candidate, entry: body.item! } : candidate)) } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update this item.') } finally { setSavingKey(null) } }
  return <details className="group/onboarding rounded-lg border border-slate-200 bg-white"><summary aria-label={`Expand ${clientName} onboarding checklist`} className="flex cursor-pointer list-none items-center justify-between gap-3 p-4 marker:hidden"><div><h3 className="text-sm font-semibold text-slate-950">Onboarding checklist</h3><p className="mt-1 text-xs text-slate-600">{completeCount} of {items.length} finished</p></div><ChevronDown aria-hidden="true" className="h-4 w-4 text-slate-400 transition group-open/onboarding:rotate-180" /></summary><div className="space-y-3 border-t border-slate-100 p-4">{items.map((item) => <article className="rounded-md border border-slate-200 p-3" key={item.key}><label className="flex cursor-pointer items-start gap-3"><input aria-label={`Mark ${item.title} complete`} checked={item.entry.isCompleted} className="mt-1 h-4 w-4 accent-slate-900" disabled={savingKey === item.key} onChange={() => void toggle(item)} type="checkbox" /><span><span className="block text-sm font-semibold text-slate-950">{item.title}</span><span className="mt-1 block text-xs leading-5 text-slate-600">{item.description}</span></span></label>{item.guidance ? <ol className="mt-3 list-decimal space-y-1 pl-8 text-xs leading-5 text-slate-700">{item.guidance.map((question) => <li key={question}>{question}</li>)}</ol> : null}</article>)}{message ? <p className="text-sm text-rose-700" role="status">{message}</p> : null}</div></details>
}
