export const recipes = [
  {
    id: 1,
    title: "Chocolate-Dipped Strawberries",
    description: "Nothing says \"celebration\" like a perfectly dipped strawberry. Heather\'s go-to recipe featuring Ghirardelli chocolate and that brilliant sandwich baggie trick for the white chocolate drizzle — a showstopper that\'s easier than it looks.",
    category: "Baking",
    prepTime: "20 minutes",
    servings: 24,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/6cd94401-dada-410b-a368-c84701068b4d_Chocolate-covered-strawberries-image-2.jpg?v=fc127c28393e4a2124f33ad6d7a67a0c",
    imagePosition: "center 15%",
    modalImagePosition: "center 30%",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7607942248457604382",
    ingredients: [
      "2 to 3 lbs firm whole strawberries (washed and thoroughly dried)",
      "1 cup Ghirardelli Semi-Sweet Chocolate Chips",
      "1 cup Ghirardelli Milk Chocolate Chips",
      "1 Tbsp refined coconut oil",
      "4 oz Ghirardelli White Melting Wafers",
      "Optional: Extra coconut oil (approx. ½ tsp) to thin the white chocolate if needed"
    ],
    steps: [
      "The Chocolate Base: Combine the semi-sweet chips, milk chocolate chips, and coconut oil in a microwave-safe bowl.",
      "Melt: Microwave on low heat in 20-second intervals. Stir often between rounds until the mixture is completely melted and smooth.",
      "The Dip: Dip each strawberry into the melted chocolate. Allow the excess to drip off, then place the berries onto a half-sheet pan lined with parchment paper.",
      "The White Drizzle: Place the white melting wafers in a separate microwave-safe bowl. Microwave on low heat in 15-second intervals, stirring often.",
      "Heather\'s Tip: If the white chocolate is too thick to drizzle, stir in a tiny bit of coconut oil (start with ½ tsp) to thin it out.",
      "The DIY Pastry Bag: Line a drinking glass with a sandwich baggie. Pour the melted white chocolate into the bag, remove it from the glass, and snip a tiny piece off the corner to create a pastry bag.",
      "Decorate: Drizzle the white chocolate in a beautiful pattern over the dark-coated berries.",
      "Set: Place in the refrigerator until the chocolate is firm and set.",
      "Serve: For the best texture, set the berries out for 30 minutes prior to eating."
    ],
    note: "The most important step in this whole recipe is making sure your strawberries are bone dry before you start. If there is even a little moisture on the skin, the chocolate won\'t stick properly! I always use Ghirardelli because the quality and shine are unbeatable for a professional look. These are an absolute indulgence, but they are definitely best enjoyed the same day they are made to keep the berries fresh and the chocolate snappy. 🍓🍫"
  },
  {
    id: 2,
    title: "Homemade Coffee Creamer",
    description: "This is a game-changer for coffee lovers. Once you realize how easy it is to make your own creamer (and how much better it tastes than the store-bought stuff with all the additives), you'll never go back.",
    category: "Drinks & Extras",
    prepTime: "10 minutes",
    servings: 16,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/6ffb3b9c-b20d-4c9e-8bfa-f891b482bcb1_Heathers-homemade-coffee-creamer-recipe-image-1.jpg?v=f906b28e5d3a8cb1bc5f83d4965b138a",
    imagePosition: "center 20%",
    modalImage: "https://readdy.ai/api/search-image?query=homemade%20vanilla%20coffee%20creamer%20in%20glass%20mason%20jar%20with%20fresh%20coffee%20cup%20beside%20it%20on%20rustic%20wooden%20table%20warm%20morning%20light%20cozy%20kitchen%20aesthetic%20simple%20clean%20background%20cream%20pouring&width=600&height=400&seq=recipe-coffee-creamer-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7543480306020486431",
    ingredients: [
      "3 cups Half & Half",
      "1 can (14 oz) Sweetened Condensed Milk",
      "2 Tbsp Pure Vanilla Extract"
    ],
    steps: [
      "Measure: Pour 3 cups of half & half into a 4-cup measuring pitcher.",
      "Sweeten: Add the entire can of sweetened condensed milk to the pitcher.",
      "Blend: Whisk the mixture vigorously until the condensed milk is thoroughly incorporated and the liquid is smooth.",
      "Flavor: Whisk in the 2 tablespoons of pure vanilla extract.",
      "Bottle: Pour the finished creamer into a 33 oz glass milk bottle (or any airtight glass container).",
      "Chill: Store in the refrigerator. It keeps perfectly for about one week."
    ],
    note: "This base recipe is your canvas! You can customize your morning cup with these easy swaps:\n\nChocolate: Whisk in unsweetened cocoa powder or a high-quality chocolate sauce like Ghirardelli or Torani to taste.\n\nCaramel: Add high-quality caramel sauce. (Pro-tip: add a pinch of salt for a Salted Caramel vibe!)\n\nPumpkin Spice: Whisk in 3 Tbsp of real pumpkin puree and 1 tsp of pumpkin pie spice.\n\nAmaretto: Reduce the vanilla to 1 tsp and whisk in 1 tsp of pure almond extract.\n\nBecause this uses fresh dairy, just keep an eye on the expiration date of your Half & Half—that\'s usually your best guide for how long the creamer will stay fresh! ☕️🥛"
  },
  {
    id: 3,
    title: "Family Pasta Sauce",
    description: "Nothing beats a slow-simmered, \"low and slow\" red sauce. This recipe is a massive batch (nearly 90oz of tomatoes!), which makes it perfect for the freezer-ready strategy Heather mentioned.",
    category: "Italian Classics",
    prepTime: "2+ hours",
    servings: 12,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/ecb20eab-b491-49c8-baca-51e1ccf54582_Homemade-pasta-sauce-image-2.jpg?v=d3a5a736c6a7082ebab4c7e337803013",
    imagePosition: "center",
    modalImage: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/b54c243f-a254-4253-bb0f-23c2ead6af32_Homemade-pasta-sauce-image-1.jpg?v=75bbd094227c3b9b9f3a7608fe3990b5",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7596702738856168735",
    ingredients: [
      "1 can (28 oz) Tomato Puree OR 1 bottle (24 oz) Passata",
      "1 can (28 oz) Tomato Sauce",
      "1 can (28 oz) Crushed Tomatoes",
      "1 medium Onion, chopped",
      "5 cloves Garlic, finely minced",
      "1 tsp dried Oregano",
      "1 tsp dried Basil",
      "2 Tbsp dried Parsley",
      "2 Tbsp Sugar",
      "1 cup Water",
      "2 Tbsp Olive Oil"
    ],
    steps: [
      "Sauté: Heat the olive oil in a large sauce pot. Add the chopped onions and sauté until they are translucent.",
      "Infuse: Add the finely minced garlic and sauté just until fragrant.",
      "Crucial Tip: Be careful NOT to brown the onions or garlic, as this will make the sauce bitter. Turn the heat down, stir frequently, and do not leave the pot unattended during this step.",
      "The Tomato Base: Add the tomato puree (or passata), tomato sauce, and crushed tomatoes to the pot. Stir until well blended.",
      "The Can Rinse: Take your 1 cup of water and use it to rinse out the remaining bits of sauce from the tomato cans, then pour that liquid into the pot.",
      "Season: Stir in the dried oregano, basil, parsley, and sugar.",
      "The Long Simmer: Bring the sauce to a simmer, then immediately reduce the heat to low to maintain a very gentle bubble.",
      "Vent & Reduce: Place the lid half-on the pot to allow steam to escape. Let it simmer for at least 2 hours.",
      "Maintenance: Every 30 minutes, give the sauce a good stir, making sure to scrape the bottom of the pot to prevent any sticking or scorching."
    ],
    note: "This is the ultimate \'set it and forget it\' Sunday sauce. The 2-hour simmer is non-negotiable — it\'s what allows the acidity of the tomatoes to mellow out and the herbs to really wake up. Since this makes a generous amount, I often double the recipe and freeze the extra in portions. It\'s a lifesaver for quick weeknight pasta, homemade pizzas, or meatball subs! Just remember: keep that heat low and the lid cracked. 🍝🍅"
  },
  {
    id: 4,
    title: "Sweet & Salty Clusters",
    description: "A dangerously good mix of salty-crunchy and sweet-smooth — Ghirardelli chocolate, dry roasted peanuts, and crushed Ruffles potato chips come together in the most addictive no-bake treat you'll ever make.",
    category: "No-Bake Treats",
    prepTime: "20 minutes",
    servings: 60,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/2d432ff0-c4cd-4fe2-89a9-b9db5f9c7a19_Sweet-and-Salty-clusters-image-1.jpg?v=37c4e68d5595dfe2db85ff142c3ce9ba",
    imagePosition: "center",
    imageScale: 0.75,
    modalImage: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/b8d542fa-6206-402e-8092-491b68ad0094_Sweet-and-Salty-Clusters-Image-2.jpg?v=cad682c89d4c05da14167354be862d7e",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7588520288032279839",
    ingredients: [
      "12 oz Ghirardelli Semi-sweet Chocolate Chips",
      "12 oz Ghirardelli Milk Chocolate Chips",
      "16 oz Dry Roasted & Salted Peanuts",
      "8\u201310 oz Ruffles Potato Chips, crushed",
      "Alternative: 24 oz Ghirardelli White Melting Wafers (for the white chocolate version)"
    ],
    steps: [
      "Melt the Chocolate: Combine the semi-sweet and milk chocolate chips in a large, microwave-safe bowl.",
      "Heat Gently: Melt the chocolate on low power, stirring every 20 seconds. Continue until the chocolate is completely smooth and glossy. Do not rush this, or the chocolate might seize!",
      "The Mix-In: Gently fold the dry roasted peanuts and the crushed Ruffles potato chips into the melted chocolate. Stir until everything is thoroughly coated in chocolatey goodness.",
      "Scoop & Portion: Drop the clusters onto a parchment-lined sheet pan or into mini muffin liners.",
      "Pro-Tip: Use a #30 scoop for this! It creates perfectly uniform clusters and should yield about 60 total.",
      "Set: Place the pan in the refrigerator and chill until the clusters are completely firm and set.",
      "Store: Keep them in an airtight container to maintain that potato chip crunch."
    ],
    note: "The key to these is the Ruffles\u2014those ridges hold onto the chocolate perfectly and provide a much better crunch than a thin chip! If you want to switch things up, these are absolutely delicious made with white chocolate instead. Just swap the chocolate chips for 24 oz of Ghirardelli White Melting Wafers. These make incredible gifts during the holidays, but honestly, they rarely last long enough to make it out of the house! \ud83c\udf6b\ud83e\udd68"
  },
  {
    id: 5,
    title: "Chocolate Raspberry Cake",
    description: "Heather\'s Daisy Sour Cream Chocolate Cake — deeply moist with real melted semi-sweet chocolate and a rich alternating batter method — layered with a from-scratch lemon raspberry filling that\'s silky, seed-free, and absolutely stunning. This is the one.",
    category: "Baking",
    prepTime: "1 hour 30 minutes (+ 4+ hours chill for filling)",
    servings: 12,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/b1c597e5-bf90-47be-949d-a4cedc48b9c8_80005953179541267561.jpg?v=78a5727578369f2a61bdb7477d5b8428",
    imagePosition: "50% 28%",
    modalImage: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/8ad57ca7-4975-4afb-9734-55afbae0e372_13230207164425892991.jpg?v=a065b91e3c4e7cc0c410ddf6c615e3a2",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7586337380358049055",
    ingredients: [
      "— DAISY SOUR CREAM CHOCOLATE CAKE —",
      "\u00be cup Vegetable Oil (148.5g)",
      "1 large Egg, room temperature",
      "2 tsp Vanilla Extract",
      "1 cup Light Brown Sugar, firmly packed (213g)",
      "\u00bd cup Granulated Sugar (99g)",
      "2 (1-oz) squares Semi-Sweet Baking Chocolate, melted & slightly cooled",
      "2 cups All-Purpose Flour (240g) \u2014 divided 1 cup + 1 cup",
      "\u2153 cup Unsweetened Cocoa Powder (56g)",
      "1 tbsp Baking Soda",
      "\u00bd tsp Salt",
      "1 cup Warm Water (227g / 8oz) \u2014 divided \u00bd cup + \u00bd cup",
      "1 cup Sour Cream, room temperature (227g)",
      "— HEATHER\'S RASPBERRY FILLING —",
      "12 oz (approx. 3 cups) Fresh or Frozen Raspberries (do not thaw if frozen)",
      "5 oz Sugar",
      "1 whole Lemon, zested",
      "1 tbsp Lemon Juice",
      "1 oz Water",
      "2 tbsp Clear Jel or Corn Starch (Tapioca Starch works as a sub)",
      "\u00bd tsp Pure Vanilla Extract"
    ],
    steps: [
      "— THE CAKE —",
      "Prep: Preheat oven to 350\u00b0F. Grease and flour your pans \u2014 8\" rounds, Bundt, 9x13, or cupcake tin all work.",
      "Base: In a large mixer bowl, beat oil, egg, and vanilla on medium for 1 minute. Add both sugars and beat for 1 more minute.",
      "The Mix: Add melted chocolate, 1 cup of the flour, cocoa powder, baking soda, and salt. Beat on low until mixed.",
      "The Alternating Step: Add \u00bd cup of the warm water and beat on low. Add the remaining 1 cup of flour and the remaining \u00bd cup of water. Scrape the sides of the bowl.",
      "Final Beat: Beat on medium speed for 2 minutes, then fold in the sour cream until fully blended.",
      "Bake: 8\" rounds \u2014 30\u201335 mins. 9x13 or Bundt \u2014 30\u201340 mins. 24 Cupcakes \u2014 approx. 15 mins. Cool in pan for 10 minutes before removing.",
      "— THE FILLING —",
      "Slurry: Whisk the starch and water together until fully dissolved.",
      "Thicken: In a saucepan over medium heat, combine berries, sugar, lemon juice, and zest. Mash the berries as they heat. Stir in the starch slurry.",
      "Boil: Bring to a boil and let it bubble for 5 full minutes, stirring occasionally.",
      "Refine: Remove from heat and stir in vanilla. For a perfectly smooth, seed-free filling, run through a food mill now.",
      "Chill: Cool at room temp for 15 minutes, then refrigerate for 4+ hours (or up to 1 week) before assembling."
    ],
    note: "The Cupcake Hack: Use a sharp knife to cut a cone-shaped circle out of the top. Fill the hole with 1\u20132 tsp of raspberry. Slice the \"point\" off the cake cone and press the flat top back on as a plug. \ud83e\uddc1 The \"Dam\" Technique: When layering, pipe a frosting dam around the edge of each layer with a Wilton 2A tip \u2014 this holds the raspberry filling (approx. \u00bd cup for an 8\" cake) in place so it doesn\'t leak out. Storage: Filling keeps 1 day at room temp or 1 week in the fridge. Can be frozen 3\u20136 months \u2014 it will be very thick when thawed. Tools: Heather recommends an offset spatula for spreading and disposable or reusable piping bags for assembly."
  },
  {
    id: 6,
    title: "Pizzelles",
    description: "Pizzelles are a classic! Traditional Italian waffle cookies — thin, crisp, and embossed with a beautiful snowflake or floral pattern from the iron. So delicate and light, they feel almost \"refreshing\" compared to a heavy chocolate chip cookie. A timeless holiday tradition.",
    category: "Baking",
    prepTime: "1 hour",
    servings: 42,
    image: "https://public.readdy.ai/ai/img_res/edited_3701a2f3c1273fa39d2a2df0681ae821_72d9db89.jpg",
    imagePosition: "center 60%",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7585436041427897631",
    ingredients: [
      "2 cups all-purpose flour",
      "1 cup granulated sugar OR packed brown sugar (Heather's tip: Brown sugar adds a deeper caramel flavor!)",
      "¾ cup (1½ sticks) butter or margarine, melted and cooled",
      "1 tablespoon anise extract OR vanilla extract",
      "2 teaspoons baking powder",
      "4 eggs, slightly beaten"
    ],
    steps: [
      "Prep the Iron: Heat your pizzelle iron according to the manufacturer's directions.",
      "Mix: In a large bowl, stir all the ingredients together until you have a smooth batter.",
      "Bake: Drop 1 tablespoon of batter onto the center of each design on the heated iron.",
      "Press: Close the iron and bake for about 30 seconds, or until the cookies are a light golden brown.",
      "Cool: Carefully remove the pizzelles from the iron (they will be soft at first!) and place them on a wire rack. They will crisp up quickly as they cool.",
      "Repeat: Continue with the remaining batter. This recipe yields about 3½ dozen cookies."
    ],
    note: "The choice of sugar really changes the vibe here — granulated sugar keeps them classic and bright, but brown sugar gives them a crispier texture and a rich, caramel-like finish. If you want to make these for a holiday spread, try cutting the cookies into fourths immediately after removing them from the iron while they're still soft. Once they cool and harden, dip the ends in melted chocolate and top with crushed nuts or festive sprinkles. It makes them look incredibly professional with very little extra effort! 🍪✨"
  },
  {
    id: 7,
    title: "Homemade Chicken Pot Pie",
    description: "This is the ultimate comfort food, especially since it uses the Crock Pot Roasted Chicken! It\'s a great way to show how one \"master recipe\" leads into another.",
    category: "Weeknight Dinners",
    prepTime: "1 hour 30 minutes",
    servings: 8,
    image: "https://static.readdy.ai/image/6521ef01a44cd5c540b1d9b66db907e8/2495a2c35088b4847a430c64f7ab011f.jpeg",
    imagePosition: "center 35%",
    modalImagePosition: "center 55%",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7581326868809338142",
    ingredients: [
      "— FOR THE CRUST (Single Recipe) —",
      "1 \u00bc cups All-Purpose Flour (150g)",
      "\u00bd tsp Salt",
      "\u00bd tsp Sugar",
      "10 Tbsp (1 \u00bc sticks) Unsalted Butter, chilled and cut into \u00bc-inch pats",
      "3\u20133 \u00bd Tbsp Ice Water",
      "Note: Heather uses 1 \u00bd to 2 recipes of this dough to cover the top of the large pot pie.",
      "— FOR THE FILLING & GRAVY —",
      "4 Chicken Breasts, roasted and shredded (Use the Crock Pot recipe!)",
      "6 medium Potatoes (Red Skin or Yukon Gold), peeled and cut into chunks",
      "6 medium Carrots, peeled and sliced",
      "1 medium Onion, diced",
      "1 bag (10 oz) Frozen Peas",
      "6 Tbsp Butter",
      "12 Tbsp Flour",
      "6 cups Chicken Stock (Use the stock from the Crock Pot chicken!)",
      "Salt, cracked Black Pepper, Onion Powder, and Parsley (to taste)"
    ],
    steps: [
      "Prep the Crust: Pulse flour, salt, and sugar in a food processor. Add chilled butter pats and pulse until it looks like cornmeal (7\u201312 seconds). Drizzle in 3 Tbsp ice water and pulse until the dough just starts to stick.",
      "Chill: Shape dough into a 4-inch disc, wrap in plastic, and refrigerate for 30 minutes.",
      "Simmer Veggies: In a pot of simmering water, cook potatoes, carrots, and onions until just tender. Drain and place them into an oversized 9x13 casserole pan.",
      "Assemble Filling: Add the shredded chicken and frozen peas to the pan with the vegetables.",
      "Make the Roux: In a saucepan, melt 6 Tbsp butter. Stir in 12 Tbsp flour and cook for a few minutes to create a roux (this removes the \"raw\" flour taste).",
      "Thicken the Gravy: Slowly whisk in the chicken stock. Continue whisking over medium heat for several minutes until the gravy is thick and smooth. Season to taste with salt, pepper, onion powder, and parsley.",
      "Combine: Pour the gravy over the chicken and veggies.",
      "Top & Bake: Roll out your chilled crust and place it over the top. Bake at 375\u00b0F for 40\u201360 minutes until the gravy is bubbly and the crust is a beautiful golden brown."
    ],
    note: "This pot pie is a labor of love, but using the chicken and stock from the Crock Pot Roasted Chicken recipe makes it so much easier (and tastier!). If you aren\'t in the mood to make dough, you can swap the topping for puff pastry or even refrigerated biscuits. If you do make the homemade crust, remember that this dough keeps in the fridge for 2 days or the freezer for 6 months \u2014 it\'s a great thing to have on hand for a rainy day! \ud83e\udd67\ud83e\udd55"
  },
  {
    id: 8,
    title: "The Perfect Oatmeal Cookie",
    description: "Thick, chewy oatmeal cookies loaded with butterscotch chips — crisp on the edges, soft in the center, and absolutely impossible to eat just one.",
    category: "Baking",
    prepTime: "35 minutes",
    servings: 24,
    image: "https://readdy.ai/api/search-image?query=thick%20chewy%20oatmeal%20cookies%20with%20butterscotch%20chips%20stacked%20on%20parchment%20paper%20homemade%20cookies%20golden%20brown%20crispy%20edges%20soft%20center%20rustic%20baking%20simple%20white%20background%20close%20up%20warm%20bakery%20lighting&width=600&height=400&seq=recipe-oatmeal-cookie-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7572653726297558302",
    ingredients: [
      "1 cup (2 sticks) unsalted butter, softened to room temperature",
      "1 cup packed brown sugar",
      "1/2 cup granulated sugar",
      "2 large eggs",
      "2 tsp pure vanilla extract",
      "1 1/2 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp cinnamon",
      "1/2 tsp salt",
      "3 cups old-fashioned rolled oats (not quick oats)",
      "1 1/2 cups butterscotch chips",
      "Optional: 1/2 cup chopped walnuts or raisins"
    ],
    steps: [
      "Preheat oven to 350°F. Line baking sheets with parchment paper.",
      "Beat softened butter, brown sugar, and granulated sugar together until light and fluffy, about 3 minutes — don't rush this step.",
      "Add eggs one at a time, beating well after each addition. Mix in the vanilla.",
      "In a separate bowl, whisk together flour, baking soda, cinnamon, and salt.",
      "Gradually add the dry ingredients to the butter mixture and mix until just combined.",
      "Fold in the rolled oats until evenly distributed throughout the dough.",
      "Fold in the butterscotch chips (and walnuts or raisins if using).",
      "Scoop dough into generous 2-tablespoon balls and place 2 inches apart on the prepared baking sheets.",
      "Gently press each ball down slightly with your palm — don't flatten completely.",
      "Bake for 10–12 minutes until the edges are golden but the centers still look slightly underdone.",
      "This is the key — pull them early! They continue cooking on the hot pan.",
      "Let cool on the pan for 5 minutes before transferring to a wire rack.",
      "Resist eating them immediately... or don't. No judgment here."
    ],
    note: "Old-fashioned rolled oats ONLY — quick oats make them mushy and sad. The butterscotch chips are the move that makes these different from every other oatmeal cookie you\'ve had. Pull them out when they still look underdone in the middle — that\'s how you get that perfect chewy center. Let the pan do the rest of the work. 🍪"
  },
  {
    id: 9,
    title: "Beer Braised Pot Roast",
    description: "This is the kind of \"set it and forget it\" meal that makes the whole house smell incredible. It\'s hearty, rich, and that beer-braised sauce is pure liquid gold.",
    category: "Weeknight Dinners",
    prepTime: "3 hours 30 minutes",
    servings: 8,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/841faff2-7fb5-4f61-a4bf-79cdd3980cd3_Beer-braised-beef-recipe-image.jpg?v=3f57acf85d9cc44e9102ba08c91d4712",
    imagePosition: "center",
    modalImage: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/4524f498-4581-422d-aa38-d52edd71ed4b_Beer-Braised-Beef-Recipe-Image-2.jpg?v=2d358cd9795e951dcb457fb8b8c59953",
    modalImagePosition: "center",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7571587396513369375",
    ingredients: [
      "3 lbs chuck roast, trimmed and cut into 3-inch chunks",
      "Kosher salt and fresh cracked black pepper",
      "2–3 Tbsp canola oil",
      "2 large sweet onions, thinly sliced",
      "1 lb carrots, peeled and bias-sliced",
      "2 (12 oz) bottles of beer",
      "2 heaping Tbsp flour",
      "3 dried bay leaves",
      "4 sprigs fresh thyme (or ¼ tsp dried)",
      "3 sprigs fresh flat-leaf parsley (or ½ tsp dried)",
      "2 cloves minced garlic"
    ],
    steps: [
      "Season & Sear: Generously season the beef chunks on all sides with salt and pepper. Heat the oil in a Dutch oven over medium heat. Brown the meat in batches so you don\'t crowd the pan, then transfer the browned beef to a plate and set it aside.",
      "Prep the Oven: Preheat your oven to 325°F.",
      "Deglaze: Add the sliced onions to the Dutch oven with 2 Tbsp of beer. Use a wooden spoon to scrape up all those delicious brown bits (fond) from the bottom of the pan.",
      "Soften: Continue cooking the onions, stirring frequently, for about 10 minutes until they are soft and golden.",
      "Thicken & Aromatics: Sprinkle in the flour and stir for 1 minute. Add the minced garlic and the remaining beer. Stir well and bring to a simmer until the liquid begins to thicken.",
      "Reassemble: Add the browned beef (and any juices that collected on the plate) back into the pot, pushing it down into the onion and beer mixture.",
      "Season & Layer: Add the bay leaves, thyme, and parsley. Taste and add a bit more salt and pepper if needed. Place the sliced carrots directly on top of the beef.",
      "The Long Braise: Cover the Dutch oven with its lid and place it in the oven. Bake for 3–4 hours until the beef is perfectly fork-tender."
    ],
    note: "The type of beer you use really changes the personality of this dish! A darker stout or porter will give you a deep, almost chocolatey richness, while a lighter amber ale keeps it a bit brighter. If you\'re feeling extra, serve this over a massive pile of garlic mashed potatoes or with a crusty loaf of bread to soak up every last drop of that gravy. Just don\'t forget to fish out the bay leaves before serving — nobody wants to crunch on those! 🍺🥩"
  },
  {
    id: 10,
    title: "The Best Chicken Salad",
    description: "Creamy, crunchy, and loaded with flavor — this classic chicken salad is perfect piled high on a croissant, tucked into a club sandwich, or served straight from the bowl with crackers.",
    category: "Weeknight Dinners",
    prepTime: "25 minutes",
    servings: 6,
    image: "https://readdy.ai/api/search-image?query=creamy%20homemade%20chicken%20salad%20in%20a%20white%20bowl%20with%20chunks%20of%20tender%20chicken%20celery%20red%20onion%20and%20fresh%20herbs%20on%20a%20bright%20clean%20white%20surface%20served%20with%20croissant%20beside%20it%20classic%20deli%20style%20lunch%20appetizing%20fresh%20simple%20background&width=600&height=400&seq=recipe-chicken-salad-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7569009828052421919",
    ingredients: [
      "2 lbs cooked chicken breast, chopped or shredded (rotisserie works great)",
      "3/4 cup mayonnaise (Duke's or Hellmann's)",
      "1 tbsp Dijon mustard",
      "2 tsp fresh lemon juice",
      "3 stalks celery, finely diced",
      "1/4 cup red onion, finely minced",
      "1/3 cup dill pickles, finely chopped (or 2 tbsp sweet relish)",
      "2 tbsp fresh dill, chopped (or 1 tsp dried dill)",
      "1/2 tsp garlic powder",
      "1/2 tsp onion powder",
      "Salt and black pepper to taste",
      "Optional: 1/4 cup dried cranberries or halved grapes for sweetness",
      "Optional: 1/4 cup chopped pecans or walnuts for crunch",
      "Croissants, toasted bread, or lettuce wraps for serving"
    ],
    steps: [
      "Cook and cool chicken completely before starting — warm chicken will make the mayo greasy. Rotisserie chicken is a total shortcut here.",
      "Chop the chicken into small, uniform bite-sized pieces — not too fine, you want some texture.",
      "In a large bowl, whisk together the mayo, Dijon mustard, lemon juice, garlic powder, and onion powder until smooth.",
      "Add the chopped chicken and toss to coat evenly with the dressing.",
      "Fold in the celery, red onion, dill pickles, and fresh dill.",
      "Add any optional mix-ins (cranberries, grapes, or nuts) if using.",
      "Taste and season generously with salt and black pepper.",
      "Cover and refrigerate for at least 30 minutes before serving — this is key, it lets all the flavors meld together.",
      "Serve on croissants, toasted sourdough, in a club sandwich, or in lettuce cups.",
      "Keeps in the fridge for up to 4 days."
    ],
    note: "Cold chicken, cold mayo, and that 30-minute rest in the fridge — those are the three non-negotiables. The Dijon and lemon juice cut through the richness of the mayo and make it taste SO much fresher and brighter than any store-bought version. The pickles are everything. Do not skip the pickles. I make a big batch every Sunday and it disappears by Tuesday. 🥗"
  },
  {
    id: 11,
    title: "Apple Coffee Cake",
    description: "A tender, cinnamon-swirled bundt cake loaded with chunks of fresh apple and topped with a sweet brown sugar streusel — the ultimate fall baking moment that makes the whole house smell incredible.",
    category: "Baking",
    prepTime: "1 hour 15 minutes",
    servings: 14,
    image: "https://readdy.ai/api/search-image?query=apple%20coffee%20cake%20bundt%20cake%20with%20cinnamon%20streusel%20topping%20and%20powdered%20sugar%20glaze%20drizzle%20on%20white%20cake%20plate%20fresh%20apples%20beside%20it%20autumn%20fall%20baking%20warm%20golden%20tones%20cozy%20kitchen%20simple%20clean%20white%20background%20beautiful%20homemade%20cake&width=600&height=400&seq=recipe-apple-coffee-cake-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7567849761961725215",
    ingredients: [
      "3 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp baking powder",
      "1 tsp fine salt",
      "1 cup (2 sticks) unsalted butter, softened",
      "1 1/2 cups granulated sugar",
      "1/2 cup packed brown sugar",
      "3/4 cup vegetable oil",
      "4 large eggs, room temperature",
      "2 tsp pure vanilla extract",
      "3 cups Granny Smith or Honeycrisp apples, peeled and diced small (about 3 apples)",
      "Streusel: 1/2 cup brown sugar, 1/3 cup flour, 1 tsp cinnamon, 4 tbsp cold butter cubed",
      "Glaze: 1 cup powdered sugar, 2–3 tbsp milk or apple cider, 1/2 tsp vanilla"
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 10-inch bundt pan very thoroughly — get into every ridge with butter and flour or baking spray.",
      "Whisk together flour, baking soda, baking powder, salt, cinnamon, ginger, nutmeg, and cloves in a bowl. Set aside.",
      "Beat softened butter, granulated sugar, and brown sugar together until very light and fluffy — about 4 minutes. Don't rush this.",
      "Add eggs one at a time, beating well after each. Mix in vanilla.",
      "Gradually add the dry ingredients to the butter mixture and mix until just combined — don't overmix.",
      "Fold in the apple chunks gently — the batter will be thick and that's exactly right.",
      "Pour half the batter into the prepared bundt pan and spread evenly.",
      "Sprinkle half the streusel over the batter layer.",
      "Add the remaining batter on top and spread carefully, then finish with the rest of the streusel.",
      "Bake for 55–65 minutes until a skewer inserted in the center comes out clean. Start checking at 55 minutes.",
      "Cool in the pan for 20 full minutes before flipping — don't rush this or the cake will break.",
      "Invert onto a wire rack and cool completely.",
      "Mix glaze ingredients until smooth and drizzle generously over the cooled cake."
    ],
    note: "Grease that bundt pan like your life depends on it — every single ridge. A torn bundt cake is a heartbreak nobody needs. The sour cream is what keeps this insanely moist for days. Honeycrisp apples hold their shape beautifully but Granny Smith gives you that tart punch against all the sweetness. Either way, this one is an absolute FALL staple. 🍎"
  },
  {
    id: 12,
    title: "My Favorite Chocolate Chip Cookies",
    description: "The only chocolate chip cookie recipe you'll ever need — crispy edges, gooey centers, loaded with chocolate chips, and absolutely perfect every single time.",
    category: "Baking",
    prepTime: "45 minutes",
    servings: 30,
    image: "https://readdy.ai/api/search-image?query=classic%20American%20chocolate%20chip%20cookies%20on%20white%20parchment%20paper%20thick%20chunky%20dough%20with%20visible%20large%20semi-sweet%20chocolate%20chips%20melted%20and%20glistening%20freshly%20baked%20golden%20buttery%20color%20warm%20natural%20light%20bright%20clean%20white%20background%20wholesome%20homemade%20bakery%20style%20no%20oats%20no%20other%20ingredients%20just%20pure%20chocolate%20chip%20perfection&width=600&height=400&seq=recipe-choc-chip-fresh-v2&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7569745760955239711",
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp fine sea salt",
      "1 cup (2 sticks) unsalted butter, softened to room temperature",
      "3/4 cup granulated sugar",
      "3/4 cup packed brown sugar",
      "2 large eggs, room temperature",
      "2 tsp pure vanilla extract",
      "2 cups (12 oz) semi-sweet chocolate chips",
      "Optional: 1/2 cup chopped walnuts or pecans",
      "Flaky sea salt for sprinkling on top"
    ],
    steps: [
      "Preheat oven to 375°F. Line baking sheets with parchment paper.",
      "Whisk together flour, baking soda, and salt in a bowl. Set aside.",
      "In a large bowl, beat softened butter, granulated sugar, and brown sugar together until light and very fluffy — about 4 full minutes. Don't rush this.",
      "Add eggs one at a time, beating well after each. Mix in vanilla.",
      "Gradually add the dry ingredients to the butter mixture and mix until just combined — don't overmix.",
      "Fold in the chocolate chips (and walnuts if using) until evenly distributed.",
      "For the best results, cover the dough and refrigerate for at least 30 minutes — this is the secret to bakery-style cookies.",
      "Scoop dough into heaping tablespoon-sized balls and place 2 inches apart on prepared baking sheets.",
      "Sprinkle each ball lightly with flaky sea salt.",
      "Bake for 9–11 minutes until the edges are golden but the centers still look slightly underdone.",
      "Pull them out — they're done even if they look soft! They firm up as they cool.",
      "Let cool on the pan for 5 minutes, then transfer to a wire rack.",
      "Try to let them cool for 10 minutes before eating. Try."
    ],
    note: "The 30-minute chill in the fridge is THE move — don't skip it if you want thick, bakery-style cookies that don't spread into flat discs. And pull them out before they look done. Always. 🍪❤️"
  },
  {
    id: 13,
    title: "My Two Best Brownie Recipes",
    description: "Two legendary brownie recipes in one — a rich, fudgy from-scratch brownie with a crinkle top, and an elevated box mix brownie with a secret upgrade. Both are outrageously good and you need both in your life.",
    category: "Baking",
    prepTime: "45 minutes",
    servings: 16,
    image: "https://readdy.ai/api/search-image?query=fudgy%20homemade%20brownies%20cut%20into%20squares%20on%20white%20parchment%20paper%20shiny%20crinkle%20top%20rich%20dark%20chocolate%20dense%20and%20gooey%20center%20close%20up%20fresh%20baked%20brownies%20simple%20clean%20white%20background%20indulgent%20chocolate%20dessert%20irresistible&width=600&height=400&seq=recipe-brownies-two-best-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7566410914572897567",
    ingredients: [
      "— FROM SCRATCH FUDGY BROWNIES —",
      "1 cup (2 sticks) unsalted butter",
      "2 cups granulated sugar",
      "4 large eggs, room temperature",
      "2 tsp pure vanilla extract",
      "1 cup unsweetened cocoa powder (Dutch-process for extra richness)",
      "1 cup all-purpose flour",
      "1 tsp salt",
      "1/2 tsp baking powder",
      "1 cup semi-sweet chocolate chips",
      "— ELEVATED BOX MIX BROWNIES —",
      "1 box your favorite brownie mix (Ghirardelli Double Chocolate recommended)",
      "1 egg (instead of however many the box says)",
      "1/2 cup melted butter (instead of oil)",
      "2 tbsp milk (instead of water)",
      "1/2 cup chocolate chips stirred in",
      "1 tsp espresso powder (the secret weapon)"
    ],
    steps: [
      "— FROM SCRATCH METHOD —",
      "Preheat oven to 350°F. Line a 9x13 pan with parchment paper, leaving an overhang on the sides.",
      "Melt butter completely in a large saucepan over medium heat. Remove from heat.",
      "Whisk sugar into the hot butter vigorously until combined — this step creates that iconic crinkle top.",
      "Let cool slightly, then whisk in eggs one at a time, followed by vanilla.",
      "Sift in cocoa powder, flour, salt, and baking powder. Fold until just combined — do not overmix.",
      "Fold in the chocolate chips, pour into the prepared pan, and spread evenly.",
      "Bake 25–30 minutes until a toothpick comes out with moist crumbs (not wet batter, not clean).",
      "— ELEVATED BOX MIX METHOD —",
      "Preheat oven to 325°F (lower than box says — this is intentional for fudgier results).",
      "Whisk together melted butter, egg, and milk until smooth.",
      "Stir in the brownie mix, espresso powder, and chocolate chips until just combined.",
      "Pour into a greased 8x8 pan — the thicker the batter, the fudgier the brownie.",
      "Bake 28–32 minutes until the edges are set and center has just a slight jiggle.",
      "— FOR BOTH —",
      "Let cool in the pan for at least 1 hour before cutting. This is the hardest part. Do it anyway.",
      "Lift out using the parchment overhang and cut with a sharp knife, wiping clean between cuts."
    ],
    note: "The crinkle top on the from-scratch version comes from that vigorous butter-sugar whisking — it's basically making a light caramel and it works every time. For the box mix version, swapping oil for butter and water for milk makes it taste completely homemade — nobody will ever know. The espresso powder doesn't make them taste like coffee, it just makes the chocolate taste MORE like chocolate. Both methods, pull them out before they look done. Always. 🍫"
  },
  {
    id: 14,
    title: "Cheesy Tortilla Soup",
    description: "A bold, smoky chicken tortilla soup loaded with melted cheese, roasted chicken, black beans, and corn — topped with crispy tortilla strips and all the fixings. Fall comfort food at its absolute finest.",
    category: "Weeknight Dinners",
    prepTime: "50 minutes",
    servings: 8,
    image: "https://readdy.ai/api/search-image?query=cheesy%20chicken%20tortilla%20soup%20in%20white%20bowl%20with%20crispy%20tortilla%20strips%20shredded%20cheese%20sour%20cream%20avocado%20and%20cilantro%20garnish%20rich%20golden%20broth%20with%20chunks%20of%20chicken%20and%20corn%20rustic%20cozy%20fall%20dinner%20warm%20lighting%20simple%20clean%20background&width=600&height=400&seq=recipe-cheesy-tortilla-soup-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7565864942096557982",
    ingredients: [
      "1 rotisserie chicken, shredded (or 2 lbs roasted chicken breast)",
      "2 cans (15 oz each) black beans, drained and rinsed",
      "1 can (15 oz) whole kernel corn, drained",
      "1 can (10 oz) Rotel diced tomatoes with green chiles",
      "1 can (28 oz) crushed tomatoes",
      "4 cups chicken broth",
      "1 block (8 oz) Velveeta or cream cheese, cubed",
      "1 cup shredded sharp cheddar cheese",
      "1 large yellow onion, diced",
      "4 cloves garlic, minced",
      "1 jalapeño, seeded and minced (optional for heat)",
      "2 tbsp olive oil",
      "1 tbsp chili powder",
      "1 tsp cumin",
      "1 tsp smoked paprika",
      "1/2 tsp garlic powder",
      "Salt and pepper to taste",
      "Toppings: tortilla strips, sour cream, shredded cheese, avocado, cilantro, lime wedges"
    ],
    steps: [
      "Heat olive oil in a large Dutch oven or soup pot over medium heat.",
      "Sauté diced onion for 5–6 minutes until softened and translucent.",
      "Add garlic and jalapeño and cook 1 more minute until fragrant.",
      "Stir in chili powder, cumin, smoked paprika, and garlic powder — toast the spices for 30 seconds.",
      "Pour in the crushed tomatoes, Rotel, and chicken broth. Stir to combine.",
      "Add drained black beans and corn. Bring to a gentle boil, then reduce to a simmer.",
      "Add the shredded rotisserie chicken and stir everything together.",
      "Drop in the cubed Velveeta or cream cheese and stir continuously until fully melted and incorporated.",
      "Stir in the shredded cheddar and let it melt in completely — this is where the magic happens.",
      "Simmer on low for 15–20 minutes to let all the flavors marry together.",
      "Taste and adjust seasoning — add more chili powder for heat, salt for depth.",
      "Ladle into bowls and pile on the toppings: tortilla strips, a dollop of sour cream, extra shredded cheese, diced avocado, fresh cilantro, and a big squeeze of lime.",
      "Serve immediately while everything is hot and melty."
    ],
    note: "The Velveeta is the move — I know, I know, but it creates this silky, glossy broth you just cannot get any other way. Rotisserie chicken makes this a weeknight no-brainer. Don't skip the smoked paprika, it gives the whole thing this incredible depth. Load up on the toppings — the crunchy tortilla strips against the creamy broth is everything. This one disappears FAST. 🫕"
  },
  {
    id: 15,
    title: "Slow Cooker Roasted Chicken",
    description: "A whole chicken slow-cooked to fall-off-the-bone perfection with a gorgeous herb butter rub — all the flavor of a Sunday roast with basically zero effort. Set it, forget it, devour it.",
    category: "Weeknight Dinners",
    prepTime: "6 hours 15 minutes",
    servings: 6,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/283928c1-8b04-4037-8840-68864008ef24_Roasted-chicken-in-a-crock-pot-image-.jpg?v=f0e266a55f667f065fcc0483ffe8233c",
    imagePosition: "center",
    modalImage: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/283928c1-8b04-4037-8840-68864008ef24_Roasted-chicken-in-a-crock-pot-image-.jpg?v=f0e266a55f667f065fcc0483ffe8233c",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7565527526122982686",
    ingredients: [
      "2 to 8 split chicken breasts — must be skin-on and bone-in for flavor",
      "1 to 2 onions, sliced",
      "Garlic salt, to taste",
      "Fresh cracked black pepper, to taste",
      "Water (approximately 4 cups)"
    ],
    steps: [
      "Layer the Base: Place a layer of sliced onions in the bottom of the Crock Pot.",
      "Season & Stack: Add a single layer of chicken on top of the onions. Season it generously with garlic salt and pepper, then add another layer of onions.",
      "Repeat: Continue layering the remaining chicken and onions, making sure the final layer on top is onions.",
      "Add Water: Gently pour the water into the Crock Pot until the level is just under the first layer of chicken (this should take about 4 cups).",
      "Crucial Warning: DO NOT cover the chicken with water. We are slow-roasting it, not boiling it!",
      "Cook: Place the lid on and cook (on either Low or High) until the chicken is a dark golden brown and the broth is bubbling. The chicken should be \"fork-tender\" and falling apart.",
      "Remove & Cool: When fully cooked, remove the chicken from the broth and set it aside to cool.",
      "Shred: Once the chicken is cool enough to handle, remove the skin and bones and shred the meat for use in your favorite recipes."
    ],
    note: "This is the \'secret ingredient\' I use for my chicken salad, pot pies, Buffalo Dip, tacos, and chicken & noodles! As a general rule of thumb, 1 large chicken breast yields about 2 cups of shredded meat. If you want to be super organized, I recommend freezing the shredded meat in 2-cup portions — it\'s the perfect amount for most recipes. Also, don\'t throw out that broth! Strain it and keep it; it creates an incredibly rich stock that freezes perfectly for future soups. 🍗🥣"
  },
  {
    id: 16,
    title: "The Best Banana Bread",
    description: "Ultra-moist, perfectly sweet banana bread loaded with chocolate chips — made as mini loaves so everyone gets their own. The browner and more spotted those bananas, the better this gets.",
    category: "Baking",
    prepTime: "1 hour 10 minutes",
    servings: 12,
    image: "https://readdy.ai/api/search-image?query=homemade%20banana%20chocolate%20chip%20bread%20mini%20loaves%20on%20white%20parchment%20paper%20golden%20brown%20crust%20moist%20tender%20crumb%20with%20melted%20chocolate%20chips%20visible%20sliced%20to%20show%20interior%20fresh%20baked%20simple%20bright%20clean%20white%20background%20warm%20natural%20light%20cozy%20baking&width=600&height=400&seq=recipe-banana-bread-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7565212827766557982",
    ingredients: [
      "3 very ripe bananas, mashed (the blacker the peel, the sweeter and better — don't use yellow ones)",
      "1/3 cup unsalted butter, melted",
      "3/4 cup granulated sugar",
      "1 large egg, beaten",
      "1 tsp pure vanilla extract",
      "1 tsp baking soda",
      "Pinch of fine salt",
      "1 1/2 cups all-purpose flour",
      "1 cup semi-sweet chocolate chips, plus more for topping",
      "Optional: 1/2 tsp cinnamon for warmth",
      "Optional: 1/2 cup chopped walnuts"
    ],
    steps: [
      "Preheat oven to 350°F. Grease a standard 9x5 loaf pan OR a mini loaf pan set (makes 3–4 mini loaves).",
      "Mash bananas thoroughly in a large bowl until almost no lumps remain — really get in there.",
      "Stir in melted butter until combined.",
      "Mix in sugar, beaten egg, and vanilla.",
      "Sprinkle baking soda and salt over the mixture and stir in.",
      "Add the flour and fold gently until just combined — a few streaks of flour are totally fine. Do NOT overmix or the bread gets tough.",
      "Fold in the chocolate chips (and walnuts if using).",
      "Pour batter into the prepared pan(s). For mini loaves, fill about 2/3 full.",
      "Scatter extra chocolate chips over the top of each loaf — this is purely for looks and it looks incredible.",
      "Bake standard loaf 55–65 minutes, mini loaves 22–28 minutes, until a toothpick inserted in the center comes out with just a few moist crumbs.",
      "If the top is browning too fast, loosely tent with foil for the last 15 minutes.",
      "Cool in the pan for 10 minutes, then turn out onto a wire rack.",
      "Mini loaves make the best gifts — wrap in parchment and tie with twine."
    ],
    note: "WAIT for those bananas to get properly black and ugly — I'm talking deeply spotted, almost brown all over. That's peak sweetness and banana flavor. The chocolate chips on top aren't optional, they melt into this gorgeous gooey layer that makes every slice look like it came from a bakery. Mini loaves are the way to go — perfect portion, perfect crust-to-crumb ratio, and they make the best gifts. 🍌🍫"
  },
  {
    id: 17,
    title: "Soft & Fluffy Dinner Rolls",
    description: "Cloud-soft Japanese milk bread dinner rolls with a buttery golden top — using the tangzhong method for the most impossibly pillowy, pull-apart rolls you've ever made at home.",
    category: "Baking",
    prepTime: "3 hours",
    servings: 12,
    image: "https://readdy.ai/api/search-image?query=soft%20fluffy%20homemade%20dinner%20rolls%20in%20baking%20pan%20pull-apart%20golden%20brown%20buttery%20tops%20Japanese%20milk%20bread%20style%20pillowy%20tender%20bread%20rolls%20fresh%20from%20oven%20simple%20clean%20white%20background%20warm%20cozy%20kitchen%20lighting%20inviting%20homemade%20bread&width=600&height=400&seq=recipe-dinner-rolls-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7564191342847397150",
    ingredients: [
      "— TANGZHONG (the secret to ultra-soft rolls) —",
      "3 tbsp all-purpose flour",
      "1/2 cup whole milk",
      "— DOUGH —",
      "2 3/4 cups all-purpose flour",
      "\u00bd cup granulated sugar",
      "\u00bd tsp fine salt",
      "2 1/4 tsp instant yeast (1 packet)",
      "1/2 cup warm whole milk (110°F — warm to the touch, not hot)",
      "1 large egg, room temperature",
      "4 tbsp unsalted butter, softened and cut into pieces",
      "— FINISH —",
      "2 tbsp unsalted butter, melted (for brushing)",
      "Flaky sea salt for topping (optional but so good)"
    ],
    steps: [
      "Make the tangzhong first: whisk flour and milk together in a small saucepan over medium heat, stirring constantly, until it thickens into a smooth paste — about 2–3 minutes. Remove from heat and let cool completely.",
      "In a large bowl, whisk together flour, sugar, salt, and instant yeast.",
      "Add the cooled tangzhong, warm milk, and egg. Mix until a shaggy dough forms.",
      "Turn dough out onto a lightly floured surface and knead for 5 minutes.",
      "Add the softened butter one piece at a time, kneading it fully into the dough before adding the next piece — this takes patience but it's worth every second.",
      "Continue kneading for another 8–10 minutes until the dough is smooth, elastic, and slightly tacky but not sticky. It should pass the windowpane test — stretch a small piece thin enough to see light through without it tearing.",
      "Shape dough into a ball, place in a lightly greased bowl, cover with plastic wrap or a damp towel, and let rise in a warm place for 1–1.5 hours until doubled.",
      "Punch the dough down and divide into 12 equal pieces (weigh them for uniformity — about 65g each).",
      "Shape each piece into a smooth, taut ball by pulling the edges to the bottom and pinching.",
      "Arrange in a greased 9x13 baking dish, spacing them just barely apart.",
      "Cover and let rise again for 45–60 minutes until they're puffed and touching each other.",
      "Preheat oven to 350°F while the rolls are doing their second rise.",
      "Bake for 20–24 minutes until deeply golden on top.",
      "Immediately brush generously with melted butter the moment they come out of the oven.",
      "Sprinkle with flaky sea salt if desired and serve warm."
    ],
    note: "The tangzhong is the entire secret — it pre-gelatinizes the starch in the flour so the rolls stay soft and fluffy for DAYS, not just a few hours. Don't skip it, it takes 3 minutes and changes everything. The windowpane test on the dough sounds fancy but it literally just means stretching it thin — if it stretches without tearing, your gluten is developed and your rolls will be perfect. These are the rolls that make people ask for the recipe at Thanksgiving. 🍞"
  },
  {
    id: 18,
    title: "Mom's Apple Betty",
    description: "A rustic, bubbling apple crisp with a thick brown sugar and oat crumble topping — warm, spiced, and deeply comforting. The recipe Mom made every fall and the one we'll never stop making.",
    category: "Baking",
    prepTime: "55 minutes",
    servings: 8,
    image: "https://readdy.ai/api/search-image?query=homemade%20apple%20betty%20apple%20crisp%20in%20white%20ceramic%20baking%20dish%20golden%20brown%20oat%20crumble%20topping%20bubbling%20cinnamon%20apple%20filling%20fall%20dessert%20served%20with%20vanilla%20ice%20cream%20scoop%20rustic%20warm%20cozy%20autumn%20simple%20clean%20background%20fresh%20parsley%20garnish&width=600&height=400&seq=recipe-moms-apple-betty-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7563421598133341471",
    ingredients: [
      "— APPLE FILLING —",
      "6 cups apples, peeled and sliced thin (Granny Smith, Honeycrisp, or a mix)",
      "1/4 cup granulated sugar",
      "2 tbsp brown sugar",
      "1 tsp ground cinnamon",
      "1/4 tsp ground nutmeg",
      "1 tbsp lemon juice",
      "1 tbsp all-purpose flour (to thicken the juices)",
      "— CRUMBLE TOPPING —",
      "1 cup old-fashioned rolled oats",
      "3/4 cup all-purpose flour",
      "3/4 cup packed brown sugar",
      "1 tsp ground cinnamon",
      "1/4 tsp fine salt",
      "1/2 cup (1 stick) cold unsalted butter, cut into small cubes",
      "— SERVING —",
      "Vanilla ice cream or fresh whipped cream"
    ],
    steps: [
      "Preheat oven to 350°F. Lightly butter a 9x13 or 9x9 baking dish.",
      "Peel and slice apples about 1/4 inch thick — not too thin or they'll turn to mush, not too thick or they won't cook through.",
      "Toss apple slices with granulated sugar, brown sugar, cinnamon, nutmeg, lemon juice, and flour until evenly coated.",
      "Pour apple mixture into the prepared baking dish and spread into an even layer.",
      "Make the crumble: combine oats, flour, brown sugar, cinnamon, and salt in a bowl and mix together.",
      "Add the cold cubed butter and work it in with your fingers, pinching and pressing until the mixture resembles coarse, clumpy crumbs. You want big chunks — don't overwork it.",
      "Spread the crumble topping evenly over the apples, covering them completely.",
      "Bake for 40–45 minutes until the topping is deep golden brown and the apple filling is bubbling up around the edges.",
      "Let cool for at least 10 minutes before serving — the filling needs to thicken up slightly.",
      "Serve warm with a big scoop of vanilla ice cream. Non-negotiable."
    ],
    note: "Mom made this every single fall and the whole house smelled like cinnamon and brown sugar for hours. The secret is mixing your apple varieties — Granny Smith for tartness and Honeycrisp for sweetness — and keeping that butter COLD for the crumble so you get those big crunchy chunks on top. The lemon juice brightens everything up and keeps the apples from getting mushy. Serve it warm with ice cream and watch it disappear in minutes. This one is pure love on a plate. 🍎❤️"
  },
  {
    id: 19,
    title: "Easy Vegetable Soup",
    description: "A total pantry superstar — the secret weapon is Spicy V8 as the base, a classic pro-mom move that adds a depth of flavor and a tiny bit of heat you just can't get from plain tomato juice.",
    category: "Weeknight Dinners",
    prepTime: "45 minutes",
    servings: 8,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/d5f272d6-53ed-4733-9086-bacb0cf347d3_Easy-vegetable-soup-Image-2.jpg?v=8a26c3d41711c494735de2ef5fd495a4",
    imagePosition: "center",
    modalImage: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/d5f272d6-53ed-4733-9086-bacb0cf347d3_Easy-vegetable-soup-Image-2.jpg?v=8a26c3d41711c494735de2ef5fd495a4",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7563025123037482271",
    ingredients: [
      "1 tablespoon butter",
      "1 tablespoon oil",
      "1 medium onion, diced",
      "2 large carrots, diced",
      "2 ribs celery, diced",
      "2 medium potatoes, diced",
      "1 clove garlic, minced",
      "4 cups beef stock",
      "1 cup water",
      "1 can (11.5 oz) Spicy V8 Juice",
      "1 can (14.5 oz) diced tomatoes (with juice)",
      "1 can (14.5 oz) cut green beans, drained",
      "1 can (14.5 oz) corn, drained",
      "\u00bd cup frozen peas",
      "\u00bd to 1 teaspoon kosher salt (to taste)",
      "\u00bc teaspoon cracked black pepper (to taste)",
      "\u00bd teaspoon dried basil",
      "\u00bd teaspoon dried parsley",
      "\u00bc teaspoon Creole or Cajun seasoning (optional, to taste)"
    ],
    steps: [
      "Saut\u00e9 the Aromatics: Heat the butter and oil in a large pot over medium-high heat. Add the onion, carrots, celery, and potatoes. Cook for about 5 minutes, stirring frequently.",
      "Add Garlic: Stir in the minced garlic and saut\u00e9 for just 1 minute until fragrant.",
      "The Liquid Base: Pour in the beef stock, water, Spicy V8, and the diced tomatoes (including the juice).",
      "The First Simmer: Bring the mixture to a boil, then reduce the heat to a simmer. Cook uncovered for 30 minutes, stirring occasionally.",
      "Veggie Toss: Add the drained green beans, drained corn, and frozen peas.",
      "Season: Stir in the salt, pepper, basil, parsley, and the Creole/Cajun seasoning if you\'re using it.",
      "Final Simmer: Return the soup to a simmer and cook for an additional 15 minutes.",
      "Serve: Ladle it up while it\'s hot!"
    ],
    note: "The real secret weapon here is the Spicy V8. It gives the broth a rich, complex kick without needing a dozen different spices. If you want to keep it even more \'pantry-friendly,\' you can swap the beef stock for vegetable stock, but the beef adds a nice heartiness that pairs perfectly with the potatoes. This is one of those soups that tastes even better the next day after the flavors have had a chance to sit in the fridge! \ud83e\udd63\ud83e\udd55"
  },
  {
    id: 20,
    title: "The Great Pumpkin Cake",
    description: "A moist, warmly spiced pumpkin layer cake with silky cream cheese frosting — the fall dessert that belongs at every Thanksgiving table. Easy enough for a weeknight, impressive enough for any celebration.",
    category: "Baking",
    prepTime: "1 hour 30 minutes",
    servings: 12,
    image: "https://readdy.ai/api/search-image?query=beautiful%20pumpkin%20spice%20layer%20cake%20with%20thick%20cream%20cheese%20frosting%20on%20white%20cake%20stand%20dusted%20with%20cinnamon%20fall%20autumn%20dessert%20rustic%20elegant%20presentation%20simple%20clean%20white%20background%20warm%20golden%20tones%20homemade%20celebration%20cake&width=600&height=400&seq=recipe-pumpkin-cake-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7561587620459924766",
    ingredients: [
      "— PUMPKIN CAKE —",
      "2 cups all-purpose flour",
      "2 tsp baking powder",
      "1 tsp baking soda",
      "1/2 tsp fine salt",
      "2 tsp ground cinnamon",
      "1 tsp ground ginger",
      "1/2 tsp ground nutmeg",
      "1/4 tsp ground cloves",
      "1 can (15 oz) pure pumpkin puree (not pumpkin pie filling)",
      "1 cup granulated sugar",
      "1/2 cup packed brown sugar",
      "3/4 cup vegetable oil",
      "4 large eggs, room temperature",
      "2 tsp pure vanilla extract",
      "— CREAM CHEESE FROSTING —",
      "16 oz (2 blocks) full-fat cream cheese, softened",
      "1/2 cup (1 stick) unsalted butter, softened",
      "4 cups powdered sugar, sifted",
      "2 tsp pure vanilla extract",
      "Pinch of salt",
      "Ground cinnamon for dusting on top"
    ],
    steps: [
      "Preheat oven to 350°F. Grease and flour two 9-inch round cake pans, or line with parchment circles.",
      "Whisk together flour, baking soda, baking powder, salt, cinnamon, ginger, nutmeg, and cloves in a bowl. Set aside.",
      "Beat softened butter, granulated sugar, and brown sugar together until very light and fluffy — about 4 minutes. Don't rush this.",
      "Add eggs one at a time, beating well after each. Mix in vanilla.",
      "Gradually add the dry ingredients to the butter mixture and mix until just combined — don't overmix.",
      "Fold in the apple chunks gently — the batter will be thick and that's exactly right.",
      "Pour half the batter into the prepared pans and spread evenly.",
      "Sprinkle half the streusel over the batter layer.",
      "Add the remaining batter on top and spread carefully, then finish with the rest of the streusel.",
      "Bake for 28–33 minutes until a toothpick comes out with moist crumbs (not wet batter, not clean).",
      "Cool in the pan for 10 minutes, then turn out onto wire racks and cool completely before frosting — completely, not just mostly.",
      "Make the frosting: beat softened cream cheese and butter together until smooth and fluffy, about 3 minutes.",
      "Add sifted powdered sugar one cup at a time, mixing on low until combined, then beat on medium until fluffy.",
      "Mix in vanilla and a pinch of salt. If it's too soft, refrigerate for 15 minutes before using.",
      "Level the cake layers if needed, then frost the top of the bottom layer generously.",
      "Stack the second layer and frost the top and sides of the entire cake.",
      "Dust the top with ground cinnamon for a beautiful finish.",
      "Refrigerate for at least 30 minutes before slicing — it slices so much cleaner cold."
    ],
    note: "Use pure pumpkin puree, NOT pumpkin pie filling — they are completely different things and the filling will wreck the balance of spices. Oil instead of butter is the secret to that incredibly moist, never-dry crumb — this cake stays perfect for days. The cream cheese frosting MUST be cold going on; if it's too soft it'll slide right off. Dust that cinnamon on top right before serving for the prettiest finish. This is one of those pies that makes people go completely silent at the table. That's how you know. 🍌🥧"
  },
  {
    id: 21,
    title: "Banana Coffee Cake",
    description: "A tender, cinnamon-swirled bundt cake loaded with chunks of fresh apple and topped with a sweet brown sugar streusel — the ultimate fall baking moment that makes the whole house smell incredible.",
    category: "Baking",
    prepTime: "1 hour 15 minutes",
    servings: 14,
    image: "https://readdy.ai/api/search-image?query=apple%20coffee%20cake%20bundt%20cake%20with%20cinnamon%20streusel%20topping%20and%20powdered%20sugar%20glaze%20drizzle%20on%20white%20cake%20plate%20fresh%20apples%20beside%20it%20autumn%20fall%20baking%20warm%20golden%20tones%20cozy%20kitchen%20simple%20clean%20white%20background%20beautiful%20homemade%20cake&width=600&height=400&seq=recipe-apple-coffee-cake-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7567849761961725215",
    ingredients: [
      "3 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp baking powder",
      "1 tsp fine salt",
      "1 cup (2 sticks) unsalted butter, softened",
      "1 1/2 cups granulated sugar",
      "1/2 cup packed brown sugar",
      "3 large eggs, room temperature",
      "2 tsp pure vanilla extract",
      "2 cups (12 oz) semi-sweet chocolate chips",
      "Optional: 1/2 cup chopped walnuts or pecans",
      "Flaky sea salt for sprinkling on top"
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 10-inch bundt pan very thoroughly — get into every ridge with butter and flour or baking spray.",
      "Whisk together flour, baking soda, baking powder, salt, cinnamon, ginger, nutmeg, and cloves in a bowl. Set aside.",
      "Beat softened butter, granulated sugar, and brown sugar together until very light and fluffy — about 4 minutes. Don't rush this.",
      "Add eggs one at a time, beating well after each. Mix in vanilla.",
      "Gradually add the dry ingredients to the butter mixture and mix until just combined — don't overmix.",
      "Fold in the chocolate chips (and walnuts if using) until evenly distributed.",
      "For the best results, cover the dough and refrigerate for at least 30 minutes — this is the secret to bakery-style cookies.",
      "Scoop dough into heaping tablespoon-sized balls and place 2 inches apart on prepared baking sheets.",
      "Sprinkle each ball lightly with flaky sea salt.",
      "Bake for 9–11 minutes until the edges are golden but the centers still look slightly underdone.",
      "Pull them out — they're done even if they look soft! They firm up as they cool.",
      "Let cool on the pan for 5 minutes, then transfer to a wire rack.",
      "Try to let them cool for 10 minutes before eating. Try."
    ],
    note: "The 30-minute chill in the fridge is THE move — don't skip it if you want thick, bakery-style cookies that don't spread into flat discs. And pull them out before they look done. Always. 🍪❤️"
  },
  {
    id: 22,
    title: "Breakfast Casserole",
    description: "Three kinds of melty cheese, savory sausage, colorful peppers, and a rich seasoned egg custard all layered over a full bag of tater tots — this is the make-ahead breakfast bake that runs the whole holiday morning.",
    category: "Breakfast",
    prepTime: "1 hour (+ overnight rest)",
    servings: 12,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/a2c53144-8203-4a66-ad8f-97b8809ee3f3_51399974793871251211.jpg?v=3cfb4fe42a458fd4f679fb00a6a30cb7",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7553840143937899806",
    ingredients: [
      "1 lb bulk breakfast sausage (mild or spicy)",
      "1 medium onion, finely diced",
      "1 red bell pepper, seeded and finely diced",
      "1 green bell pepper, seeded and finely diced",
      "4 large eggs",
      "1 cup whole milk",
      "1/2 cup half & half",
      "1/4 tsp seasoned salt (like Lawry's)",
      "1/4 tsp cayenne pepper (optional)",
      "Salt and black pepper to taste",
      "2 cups shredded cheddar or cojack cheese, divided",
      "1 cup shredded pepper jack cheese, divided",
      "1 bag (32 oz) frozen tater tots"
    ],
    steps: [
      "Brown and crumble the breakfast sausage in a skillet. Once cooked through, remove from the skillet and drain on paper towels.",
      "Sauté the finely diced onion and peppers in the same skillet (use the sausage drippings for extra flavor!) until they are softened.",
      "Prep the dish: Butter a 9x13 baking dish and line the bottom completely with a single layer of tater tots.",
      "Layer: Spread the crumbled sausage, sautéed onions, peppers, and half of both cheeses over the tater tots.",
      "Whisk the base: In a large measuring pitcher or bowl, whisk together the eggs, milk, half & half, cayenne (if using), seasoned salt, and a pinch of salt and pepper.",
      "Assemble: Pour the egg mixture evenly over the casserole and top with the remaining shredded cheeses.",
      "Rest or Bake: Cover the dish tightly with foil. You can bake it immediately, or for the best results, refrigerate it overnight to let the flavors meld.",
      "Bake: Preheat your oven to 350°F. Bake covered for 25 minutes.",
      "Finish: Remove the foil and bake for an additional 25–30 minutes until the cheese is bubbly and the top is a beautiful golden brown."
    ],
    note: "This casserole is a total crowd-pleaser and is actually just as delicious without the sausage if you want a vegetarian version! If you have the time, I highly recommend prepping this the night before and letting it rest in the fridge — it gives the tater tots time to soak up that seasoned egg mixture for a much richer flavor. Just make sure you don't skip that last step of removing the foil; that's the secret to getting the cheese perfectly bubbly and the edges nice and crispy. 🍳🧀"
  },
  {
    id: 23,
    title: "Apple-Braised Pork Chops with Mashed Potatoes",
    description: "Pork chops seared golden and then slow-braised in a full bottle of apple juice with sweet onions until fork-tender — the sauce reduces into a rich, dark glaze that makes the whole house smell absolutely incredible.",
    category: "Weeknight Dinners",
    prepTime: "2 hours 15 minutes",
    servings: 6,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/da9c0e80-6291-48f3-a7a9-fa230f5bbcf3_Apple-Braised-Pork-Chops-Recipe.jpg?v=458f8eca4824eb164ed58236d51a4564",
    imagePosition: "center",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7550855016953810207",
    ingredients: [
      "4 to 8 boneless pork loin chops, rinsed and patted dry",
      "1 to 2 tbsp mild cooking oil",
      "Garlic salt, to taste",
      "Fresh cracked black pepper, to taste",
      "1 to 2 sweet onions, thinly sliced",
      "2 garlic cloves, minced",
      "1 jalapeño, seeded and minced (optional for heat)",
      "1 bottle (64 oz) 100% apple juice"
    ],
    steps: [
      "Season: Generously coat both sides of the pork chops with garlic salt and fresh cracked black pepper.",
      "Sear: Heat the cooking oil in a large nonstick pan or electric skillet over medium-high heat. Brown the chops for about 3–5 minutes per side until they have a nice golden crust.",
      "Deglaze & Layer: Once browned, pour in enough apple juice to almost cover the chops. Stir in the minced garlic and lay the sliced sweet onions directly on top of the meat.",
      "Boil & Simmer: Bring the liquid to a quick boil, then immediately reduce to a simmer and cover the pan.",
      "Braise: Let them simmer for 1½ to 2 hours. This \"low and slow\" method is what makes them so tender!",
      "Monitor: Check the pan occasionally. If the liquid gets too low, add a splash more apple juice. You\'ll notice the sauce reducing and turning a deep, dark color — that\'s pure flavor.",
      "Serve: They are ready when the pork is officially \"fork-tender.\""
    ],
    note: "The real magic here happens in the last 30 minutes! As that apple juice reduces, it transforms into a rich, dark glaze that is incredible spooned over the onions and pork. This is one of those recipes that makes the whole house smell like home. If you\'re looking for the ultimate comfort meal, serve these alongside some mashed potatoes to soak up every bit of that apple reduction. 🍎🥘"
  },
  {
    id: 24,
    title: "Peanut Butter Pie",
    description: "A dreamy, no-bake peanut butter pie with a Nutter Butter cookie crust, silky cream cheese peanut butter filling, and a chocolate ganache drizzle on top. Rich, creamy, and completely over the top in the best way.",
    category: "Baking",
    prepTime: "30 minutes",
    servings: 10,
    image: "https://readdy.ai/api/search-image?query=no-bake%20peanut%20butter%20pie%20in%20pie%20dish%20with%20Nutter%20Butter%20cookie%20crust%20creamy%20peanut%20butter%20filling%20chocolate%20ganache%20drizzle%20on%20top%20slice%20cut%20showing%20layers%20elegant%20dessert%20simple%20clean%20white%20background%20bright%20natural%20light%20indulgent%20homemade%20pie&width=600&height=400&seq=recipe-peanut-butter-pie-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7550109936806557982",
    ingredients: [
      "— NUTTER BUTTER CRUST —",
      "1 package (16 oz) Nutter Butter cookies",
      "5 tbsp unsalted butter, melted",
      "— PEANUT BUTTER FILLING —",
      "8 oz full-fat cream cheese, softened to room temperature",
      "1 1/2 cups creamy peanut butter (not natural — Jif or Skippy work best)",
      "1 1/2 cups powdered sugar, sifted",
      "1 tsp pure vanilla extract",
      "1/4 tsp fine salt",
      "1 1/2 cups heavy whipping cream, very cold",
      "— CHOCOLATE GANACHE DRIZZLE —",
      "4 oz semi-sweet chocolate, chopped",
      "1/4 cup heavy cream",
      "— TOPPING —",
      "Crushed Nutter Butter cookies for garnish",
      "Flaky sea salt (optional but incredible)"
    ],
    steps: [
      "Make the crust: pulse Nutter Butter cookies in a food processor until fine crumbs form. You should have about 2 1/2 cups of crumbs.",
      "Mix crumbs with melted butter until the mixture resembles wet sand and holds together when pressed.",
      "Press firmly and evenly into a 9-inch pie dish, covering the bottom and sides completely. Really pack it in.",
      "Freeze the crust for 15 minutes while you make the filling — this sets it so it doesn't crumble when you fill it.",
      "Beat softened cream cheese in a large bowl until completely smooth — no lumps allowed.",
      "Add peanut butter, sifted powdered sugar, vanilla, and salt. Beat together until fluffy and well combined.",
      "In a separate cold bowl, whip the heavy cream to stiff peaks.",
      "Gently fold the whipped cream into the peanut butter mixture in two additions — keep it light and airy, don't deflate it.",
      "Pour the filling into the chilled crust and spread into an even, smooth layer.",
      "Refrigerate for at least 4 hours, or overnight for best results.",
      "Make the ganache: heat heavy cream in a small saucepan until just steaming. Pour over chopped chocolate, let sit 1 minute, then stir until silky smooth.",
      "Let ganache cool slightly until it's thick enough to drizzle but still pourable.",
      "Drizzle chocolate ganache over the set pie in any pattern you like.",
      "Crush a few extra Nutter Butters and scatter over the top. Sprinkle with flaky sea salt if using.",
      "Keep refrigerated until serving. Slice with a hot, clean knife for clean cuts."
    ],
    note: "Do NOT use natural peanut butter here — the oil separation will completely wreck the texture of the filling. Jif or Skippy all the way. The overnight chill is where this goes from good to absolutely perfect — the filling sets into this luxurious, almost mousse-like texture that slices clean and holds its shape. The flaky sea salt on top against all that sweetness and chocolate is a game changer. This pie has zero business being as good as it is. 🥜🍫"
  },
  {
    id: 25,
    title: "Family's Favorite Strawberry Salad",
    description: "A stunning strawberry salad with candied pecans, creamy goat cheese or feta, red onion, and a sweet balsamic poppy seed dressing — fresh, vibrant, and the one everyone requests at every gathering.",
    category: "Weeknight Dinners",
    prepTime: "20 minutes",
    servings: 6,
    image: "https://readdy.ai/api/search-image?query=fresh%20strawberry%20salad%20in%20white%20bowl%20with%20sliced%20strawberries%20candied%20pecans%20crumbled%20goat%20cheese%20red%20onion%20and%20mixed%20greens%20bright%20colorful%20summer%20salad%20elegant%20presentation%20simple%20clean%20white%20background%20natural%20daylight%20vibrant%20fresh%20beautiful&width=600&height=400&seq=recipe-strawberry-salad-01&orientation=landscape",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7546023445339901471",
    ingredients: [
      "— SALAD —",
      "6 cups mixed greens or baby spinach (or a combination)",
      "2 cups fresh strawberries, hulled and sliced",
      "1/2 cup red onion, very thinly sliced",
      "1/2 cup crumbled goat cheese or feta cheese",
      "1/2 cup candied pecans or candied walnuts",
      "1/2 cup sliced almonds, toasted",
      "Optional: 1/2 avocado, sliced",
      "— BALSAMIC POPPY SEED DRESSING —",
      "3 tbsp balsamic vinegar",
      "1 tbsp honey",
      "1 tsp Dijon mustard",
      "1 small clove garlic, minced",
      "1/3 cup olive oil",
      "1 tsp poppy seeds",
      "Salt and pepper to taste",
      "— QUICK CANDIED PECANS (if making from scratch) —",
      "1 cup pecan halves",
      "3 tbsp granulated sugar",
      "1 tbsp butter",
      "Pinch of salt and cayenne"
    ],
    steps: [
      "If making candied pecans from scratch: melt butter and sugar in a skillet over medium heat, add pecans and stir constantly for 3–4 minutes until coated and caramelized. Spread on parchment to cool completely.",
      "Make the dressing: whisk together balsamic vinegar, honey, Dijon, and garlic until combined.",
      "Slowly drizzle in olive oil while whisking continuously until emulsified and smooth.",
      "Stir in poppy seeds and season with salt and pepper. Taste and adjust — add more honey if you want it sweeter.",
      "Soak sliced red onion in cold water for 5–10 minutes to mellow the sharpness, then drain and pat dry.",
      "Add mixed greens to a large serving bowl.",
      "Arrange sliced strawberries, drained red onion, and avocado (if using) over the greens.",
      "Scatter the candied pecans, toasted almonds, and crumbled goat cheese over everything.",
      "Drizzle dressing over the salad right before serving — don't dress it ahead or it'll wilt.",
      "Toss gently at the table and serve immediately."
    ],
    note: "The cold water soak on the red onion is a game changer — takes away that sharp bite and makes it actually enjoyable even for people who claim they don't like raw onion. Make the dressing ahead and keep it in a jar in the fridge — it keeps for a week and is incredible on everything. Don't dress the salad until right before you serve it. The candied pecans are the crown jewel and honestly worth making from scratch, but store-bought works in a pinch. This one disappears faster than anything else on the table every single time. 🍓"
  },
  {
    id: 27,
    title: "Perfect No-Mess Crispy Bacon",
    description: "This is the \"Holy Grail\" of kitchen tips. Once you start making bacon this way, you'll never deal with a greasy stovetop or a painful oil splatter ever again.",
    category: "Drinks & Extras",
    prepTime: "25 minutes",
    servings: 6,
    image: "https://storage.readdy-site.link/project_files/e169fbd4-fa75-4b71-b359-58c184778961/796019f5-4ddc-45b8-8435-af90386cdd33_No-mess-crispy-oven-bacon-recipe-image-2.jpg?v=aebd915d83731ee78ae5a977abb86ccc",
    imagePosition: "40% center",
    tiktokUrl: "https://www.tiktok.com/@blingkitchen/video/7542640784483290398",
    ingredients: [
      "12 oz package Uncured Bacon",
      "Heavy Duty Aluminum Foil",
      "Parchment Paper",
      "Half Sheet Pan"
    ],
    steps: [
      "Preheat: Set your oven to 350°F.",
      "The \"No Mess\" Foundation: Line your half sheet pan with heavy duty aluminum foil. Be extra careful not to tear the foil — the goal is to keep all the grease contained on top of the foil for easy cleanup!",
      "Arrange: Lay the bacon strips out in a single layer. It is perfectly fine if the pieces touch, but make sure they do not overlap so they cook evenly.",
      "The Splatter Guard: Place a piece of parchment paper directly on top of the bacon. This is the secret step that prevents grease from splattering all over the inside of your oven.",
      "Bake: Slide the pan into the oven for 30 minutes, then check it.",
      "Customize Your Crunch: If you like your bacon very crispy (like Heather does!), leave it in for a total of about 40 minutes.",
      "Drain: Immediately remove the bacon from the pan and place it on paper towels to drain and finish crisping up.",
      "The Easy Peasy Cleanup: Let the bacon grease cool on the pan until it solidifies. Then, simply roll up the foil and throw it away. Your pan stays clean!"
    ],
    note: "This really is the ultimate way to cook bacon for a crowd (or just a very hungry Saturday morning). The parchment paper on top is a total game-changer — it keeps the bacon flat and the oven spotless. Plus, since you're using heavy-duty foil, the cleanup takes about five seconds. If you're feeling fancy, you can sprinkle a little cracked black pepper or a tiny bit of brown sugar on the bacon before putting the parchment paper on for a 'candied' vibe! 🥓✨"
  }
];
