import type { ChecklistGroup, ChecklistStep, NicNacAnswer, Resource } from './types';

export const groups: ChecklistGroup[] = [
  'Get Set Up',
  'Learn the Back Office',
  'Get Supplies Ready',
  'Prepare for First Live',
  'Ship and Follow Up',
  'Questions for Brittany',
];

export const resources: Resource[] = [
  {
    id: 'bp-enrollment-guide',
    title: 'Bomb Party New Rep Enrollment Guide',
    description: 'Official guide for enrolling as a Party Rep.',
    url: 'https://bombpartyassets.blob.core.windows.net/exigoresourcelibraryassets/Enrolling%20as%20a%20Party%20Rep-2024.pdf',
    sourceType: 'official',
  },
  {
    id: 'bpu-enrollment-guide',
    title: 'Bomb Party University Login Guide',
    description: 'Official BPU enrollment and Teachable login walkthrough.',
    url: 'https://bombpartyassets.blob.core.windows.net/exigoresourcelibraryassets/How%20to%20Guide%20Your%20Downline%20Through%20the%20BPU%20Enrollment%20Process%2011.1.24.pdf',
    sourceType: 'official',
  },
  {
    id: 'bp-income-disclosure',
    title: 'Bomb Party Income Disclosure Statement',
    description: 'Official income disclosure for compliance-aware business basics.',
    url: 'https://bombpartyassets.blob.core.windows.net/exigoresourcelibraryassets/Rep%20Use%20Documents/Bomb%20Party_Income%20Disclosure%20Statement_2025%20%281%29.pdf',
    sourceType: 'official',
  },
  {
    id: 'bp-shipping-policy',
    title: 'Bomb Party Shipping Policy',
    description: 'Official shipping policy resource.',
    url: 'https://bombpartysupport.zendesk.com/hc/en-us/articles/33220290467732-Shipping-Policy',
    sourceType: 'official',
  },
  {
    id: 'bp-return-policy',
    title: 'Bomb Party Return Policy',
    description: 'Official return and reveal issue policy resource.',
    url: 'https://help.bombparty.com/hc/en-us/articles/33194356359444-Return-Policy',
    sourceType: 'official',
  },
  {
    id: 'ftc-mlm-guidance',
    title: 'FTC MLM Guidance',
    description: 'Plain compliance backstop for avoiding income and lifestyle claims.',
    url: 'https://www.ftc.gov/business-guidance/resources/business-guidance-concerning-multi-level-marketing',
    sourceType: 'official',
  },
  {
    id: 'sample-dashboard-note',
    title: 'Sample Team Note: Back Office Tour',
    description: 'Demo-only guidance until Brittany approves or replaces it.',
    url: '',
    sourceType: 'team',
  },
  {
    id: 'sample-live-show-note',
    title: 'Sample Team Note: First Live Prep',
    description: 'Demo-only guidance until Brittany approves or replaces it.',
    url: '',
    sourceType: 'team',
  },
  {
    id: 'sparkle-suite-preview',
    title: 'Sparkle Suite Next Step',
    description: 'Soft handoff for reps who are ready for a public site, customer resources, live queue, and trade board tools.',
    url: '',
    sourceType: 'sparkle-suite',
  },
];

export const steps: ChecklistStep[] = [
  {
    id: 'bpu-login',
    group: 'Get Set Up',
    title: 'Log into Bomb Party University',
    shortTitle: 'BPU login',
    dayWindow: 'Day 1',
    whatToDo: 'Open the BPU email from Bomb Party, sign in through Teachable, and open your first training.',
    whyItMatters: 'BPU is where Bomb Party keeps official training. This checklist helps you keep track, but BPU is still the official source.',
    resourceIds: ['bpu-enrollment-guide'],
    brittanyNote: 'Sample Brittany note: Do this before worrying about your first live. It answers basics you will need later.',
    nicNacHint: 'Ask me where to find BPU or what to do after you log in.',
  },
  {
    id: 'enrollment-check',
    group: 'Get Set Up',
    title: 'Confirm your enrollment is complete',
    shortTitle: 'Enrollment check',
    dayWindow: 'Day 1',
    whatToDo: 'Make sure your rep account, store name, starter pack, and required agreement steps are complete.',
    whyItMatters: 'You need the official setup finished before you can focus on shows and customers.',
    resourceIds: ['bp-enrollment-guide'],
    brittanyNote: 'Sample Brittany note: If anything looks weird in enrollment, ask before clicking around for an hour.',
    nicNacHint: 'Ask me what to check before you call enrollment finished.',
  },
  {
    id: 'business-basics',
    group: 'Learn the Back Office',
    title: 'Understand the money basics',
    shortTitle: 'Money basics',
    dayWindow: 'Week 1',
    whatToDo: 'Review the income disclosure and write down any questions about costs, commissions, inventory, or business expenses.',
    whyItMatters: 'This is a business. You should understand costs and avoid anyone making promises about guaranteed income.',
    resourceIds: ['bp-income-disclosure', 'ftc-mlm-guidance'],
    brittanyNote: 'Sample Brittany note: Do not overbuy inventory just because you are excited. Ask me before making a big spend.',
    nicNacHint: 'Ask me where the income disclosure is. I will send spending advice to Brittany.',
  },
  {
    id: 'dashboard-tour',
    group: 'Learn the Back Office',
    title: 'Find the important places in your rep dashboard',
    shortTitle: 'Back office tour',
    dayWindow: 'Week 1',
    whatToDo: 'Find where orders, customer details, inventory, support, billing, and BPU links live in your Bomb Party back office.',
    whyItMatters: 'Most early confusion comes from not knowing where to click.',
    resourceIds: ['sample-dashboard-note'],
    brittanyNote: 'Sample Brittany note: We will replace this with screenshots or a quick walkthrough after Brittany confirms the current dashboard.',
    nicNacHint: 'Ask me for a plain-English tour checklist.',
  },
  {
    id: 'supplies-ready',
    group: 'Get Supplies Ready',
    title: 'Gather your first-live supplies',
    shortTitle: 'Supplies ready',
    dayWindow: 'Before first live',
    whatToDo: 'Set aside your fizz setup, phone or camera, lighting, labels or packaging supplies, and a clean packing area.',
    whyItMatters: 'A calm setup makes your first live feel much easier.',
    resourceIds: ['sample-live-show-note'],
    brittanyNote: 'Sample Brittany note: Keep it simple. Good lighting and a steady phone matter more than a fancy setup.',
    nicNacHint: 'Ask me for the simple first-live supply list.',
  },
  {
    id: 'first-live-run',
    group: 'Prepare for First Live',
    title: 'Practice your first live flow',
    shortTitle: 'First live flow',
    dayWindow: 'Before first live',
    whatToDo: 'Practice your greeting, how you explain ordering, how you reveal, and what you say when the room is quiet.',
    whyItMatters: 'Practicing the flow helps you avoid freezing when people are watching.',
    resourceIds: ['sample-live-show-note'],
    brittanyNote: 'Sample Brittany note: Quiet rooms happen. Keep talking, explain what you are doing, and do not panic.',
    nicNacHint: 'Ask me for a simple run-of-show for your first live.',
  },
  {
    id: 'shipping-basics',
    group: 'Ship and Follow Up',
    title: 'Review shipping and return basics',
    shortTitle: 'Shipping basics',
    dayWindow: 'First orders',
    whatToDo: 'Open the official shipping and return resources. Save the links so you know where to check later.',
    whyItMatters: 'Customers will ask shipping and reveal issue questions. Use official resources instead of guessing.',
    resourceIds: ['bp-shipping-policy', 'bp-return-policy'],
    brittanyNote: 'Sample Brittany note: When policy details matter, check the official page before answering a customer.',
    nicNacHint: 'Ask me for the official shipping or return link.',
  },
  {
    id: 'sparkle-suite-ready',
    group: 'Questions for Brittany',
    title: 'Ask when you are ready for rep tools',
    shortTitle: 'Future tools',
    dayWindow: 'After basics',
    whatToDo: 'When your basics are in place, ask Brittany what tools can help with your public site, customer resources, and live workflow.',
    whyItMatters: 'The right tools are helpful after the basics are steady. They should not distract from getting started.',
    resourceIds: ['sparkle-suite-preview'],
    brittanyNote: 'Sample Brittany note: Sparkle Suite may help with your public site, live queue, customer info, and trade board when you are ready.',
    nicNacHint: 'Ask me what Sparkle Suite can help with after your setup is done.',
  },
];

export const nicNacAnswers: NicNacAnswer[] = [
  {
    id: 'bpu',
    triggers: ['bpu', 'university', 'teachable', 'login', 'training'],
    response: 'BPU is Bomb Party University. Start with the official login guide, then come back here and mark the step done.',
    resourceIds: ['bpu-enrollment-guide'],
    shouldEscalate: false,
  },
  {
    id: 'enrollment',
    triggers: ['enroll', 'enrollment', 'starter', 'store name', 'agreement'],
    response: 'For enrollment, use the official new rep enrollment guide. Make sure your account, store name, starter pack, and agreement steps are complete.',
    resourceIds: ['bp-enrollment-guide'],
    shouldEscalate: false,
  },
  {
    id: 'dashboard',
    triggers: ['dashboard', 'back office', 'orders', 'billing', 'inventory'],
    response: 'For your back office tour, find orders, customer details, inventory, support, billing, and the BPU link. If your screen looks different, save that for Brittany.',
    resourceIds: ['sample-dashboard-note'],
    shouldEscalate: false,
  },
  {
    id: 'supplies',
    triggers: ['supplies', 'equipment', 'lighting', 'phone', 'camera', 'labels', 'packaging'],
    response: 'Keep the first setup simple: steady phone or camera, good lighting, fizz setup, labels or packaging supplies, and a clean packing area.',
    resourceIds: ['sample-live-show-note'],
    shouldEscalate: false,
  },
  {
    id: 'live',
    triggers: ['live', 'tiktok', 'facebook', 'show', 'quiet room', 'script'],
    response: 'Before your first live, practice your greeting, ordering explanation, reveal flow, and what you will say if the room is quiet.',
    resourceIds: ['sample-live-show-note'],
    shouldEscalate: false,
  },
  {
    id: 'shipping',
    triggers: ['shipping', 'ship', 'tracking', 'label'],
    response: 'For shipping questions, start with the official Bomb Party shipping policy. For a specific customer order, ask Brittany or Bomb Party support.',
    resourceIds: ['bp-shipping-policy'],
    shouldEscalate: false,
  },
  {
    id: 'returns',
    triggers: ['return', 'damaged', 'defective', 'replace', 'replacement'],
    response: 'For returns or reveal issues, use the official return policy. Do not guess on policy details.',
    resourceIds: ['bp-return-policy'],
    shouldEscalate: false,
  },
  {
    id: 'money',
    triggers: ['income', 'money', 'profit', 'commission', 'tax', 'taxes', 'guarantee', 'spend', 'inventory buy'],
    response: 'Money questions need careful answers. Review the official income disclosure, and I saved this as a question for Brittany if you need personal guidance.',
    resourceIds: ['bp-income-disclosure', 'ftc-mlm-guidance'],
    shouldEscalate: true,
  },
  {
    id: 'sparkle-suite',
    triggers: ['website', 'live queue', 'customers', 'trade board', 'sparkle suite', 'rep tools'],
    response: 'Sparkle Suite can help reps with a public site, customer resources, live queue support, and future tools once the basics are in place. For now, finish your Start Strong setup first.',
    resourceIds: ['sparkle-suite-preview'],
    shouldEscalate: false,
  },
];
